package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DriveState.proto

public final class DriveStateOuterClass {
  private DriveStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DriveStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DriveState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *驾驶状态,0 表示手动驾驶,1表示自动驾驶
     * </pre>
     *
     * <code>int32 driveStatue = 1;</code>
     */
    int getDriveStatue();

    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    java.util.List<ExtraOuterClass.Extra> 
        getExtraList();
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    ExtraOuterClass.Extra getExtra(int index);
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    int getExtraCount();
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    java.util.List<? extends ExtraOuterClass.ExtraOrBuilder> 
        getExtraOrBuilderList();
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    ExtraOuterClass.ExtraOrBuilder getExtraOrBuilder(
            int index);
  }
  /**
   * <pre>
   *驾驶状态
   * </pre>
   *
   * Protobuf type {@code DriveState}
   */
  public  static final class DriveState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DriveState)
      DriveStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DriveState.newBuilder() to construct.
    private DriveState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DriveState() {
      driveStatue_ = 0;
      extra_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DriveState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              driveStatue_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                extra_ = new java.util.ArrayList<ExtraOuterClass.Extra>();
                mutable_bitField0_ |= 0x00000002;
              }
              extra_.add(
                  input.readMessage(ExtraOuterClass.Extra.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          extra_ = java.util.Collections.unmodifiableList(extra_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DriveStateOuterClass.internal_static_DriveState_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DriveStateOuterClass.internal_static_DriveState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DriveStateOuterClass.DriveState.class, DriveStateOuterClass.DriveState.Builder.class);
    }

    private int bitField0_;
    public static final int DRIVESTATUE_FIELD_NUMBER = 1;
    private int driveStatue_;
    /**
     * <pre>
     *驾驶状态,0 表示手动驾驶,1表示自动驾驶
     * </pre>
     *
     * <code>int32 driveStatue = 1;</code>
     */
    public int getDriveStatue() {
      return driveStatue_;
    }

    public static final int EXTRA_FIELD_NUMBER = 2;
    private java.util.List<ExtraOuterClass.Extra> extra_;
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    public java.util.List<ExtraOuterClass.Extra> getExtraList() {
      return extra_;
    }
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    public java.util.List<? extends ExtraOuterClass.ExtraOrBuilder>
        getExtraOrBuilderList() {
      return extra_;
    }
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    public int getExtraCount() {
      return extra_.size();
    }
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    public ExtraOuterClass.Extra getExtra(int index) {
      return extra_.get(index);
    }
    /**
     * <code>repeated .Extra extra = 2;</code>
     */
    public ExtraOuterClass.ExtraOrBuilder getExtraOrBuilder(
        int index) {
      return extra_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (driveStatue_ != 0) {
        output.writeInt32(1, driveStatue_);
      }
      for (int i = 0; i < extra_.size(); i++) {
        output.writeMessage(2, extra_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (driveStatue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, driveStatue_);
      }
      for (int i = 0; i < extra_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, extra_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DriveStateOuterClass.DriveState)) {
        return super.equals(obj);
      }
      DriveStateOuterClass.DriveState other = (DriveStateOuterClass.DriveState) obj;

      boolean result = true;
      result = result && (getDriveStatue()
          == other.getDriveStatue());
      result = result && getExtraList()
          .equals(other.getExtraList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DRIVESTATUE_FIELD_NUMBER;
      hash = (53 * hash) + getDriveStatue();
      if (getExtraCount() > 0) {
        hash = (37 * hash) + EXTRA_FIELD_NUMBER;
        hash = (53 * hash) + getExtraList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DriveStateOuterClass.DriveState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DriveStateOuterClass.DriveState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DriveStateOuterClass.DriveState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DriveStateOuterClass.DriveState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DriveStateOuterClass.DriveState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DriveStateOuterClass.DriveState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DriveStateOuterClass.DriveState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DriveStateOuterClass.DriveState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DriveStateOuterClass.DriveState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DriveStateOuterClass.DriveState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DriveStateOuterClass.DriveState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DriveStateOuterClass.DriveState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DriveStateOuterClass.DriveState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *驾驶状态
     * </pre>
     *
     * Protobuf type {@code DriveState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DriveState)
        DriveStateOuterClass.DriveStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DriveStateOuterClass.internal_static_DriveState_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DriveStateOuterClass.internal_static_DriveState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DriveStateOuterClass.DriveState.class, DriveStateOuterClass.DriveState.Builder.class);
      }

      // Construct using DriveStateOuterClass.DriveState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExtraFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        driveStatue_ = 0;

        if (extraBuilder_ == null) {
          extra_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          extraBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DriveStateOuterClass.internal_static_DriveState_descriptor;
      }

      public DriveStateOuterClass.DriveState getDefaultInstanceForType() {
        return DriveStateOuterClass.DriveState.getDefaultInstance();
      }

      public DriveStateOuterClass.DriveState build() {
        DriveStateOuterClass.DriveState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DriveStateOuterClass.DriveState buildPartial() {
        DriveStateOuterClass.DriveState result = new DriveStateOuterClass.DriveState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.driveStatue_ = driveStatue_;
        if (extraBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            extra_ = java.util.Collections.unmodifiableList(extra_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.extra_ = extra_;
        } else {
          result.extra_ = extraBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DriveStateOuterClass.DriveState) {
          return mergeFrom((DriveStateOuterClass.DriveState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DriveStateOuterClass.DriveState other) {
        if (other == DriveStateOuterClass.DriveState.getDefaultInstance()) return this;
        if (other.getDriveStatue() != 0) {
          setDriveStatue(other.getDriveStatue());
        }
        if (extraBuilder_ == null) {
          if (!other.extra_.isEmpty()) {
            if (extra_.isEmpty()) {
              extra_ = other.extra_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureExtraIsMutable();
              extra_.addAll(other.extra_);
            }
            onChanged();
          }
        } else {
          if (!other.extra_.isEmpty()) {
            if (extraBuilder_.isEmpty()) {
              extraBuilder_.dispose();
              extraBuilder_ = null;
              extra_ = other.extra_;
              bitField0_ = (bitField0_ & ~0x00000002);
              extraBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExtraFieldBuilder() : null;
            } else {
              extraBuilder_.addAllMessages(other.extra_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DriveStateOuterClass.DriveState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DriveStateOuterClass.DriveState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int driveStatue_ ;
      /**
       * <pre>
       *驾驶状态,0 表示手动驾驶,1表示自动驾驶
       * </pre>
       *
       * <code>int32 driveStatue = 1;</code>
       */
      public int getDriveStatue() {
        return driveStatue_;
      }
      /**
       * <pre>
       *驾驶状态,0 表示手动驾驶,1表示自动驾驶
       * </pre>
       *
       * <code>int32 driveStatue = 1;</code>
       */
      public Builder setDriveStatue(int value) {

        driveStatue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *驾驶状态,0 表示手动驾驶,1表示自动驾驶
       * </pre>
       *
       * <code>int32 driveStatue = 1;</code>
       */
      public Builder clearDriveStatue() {

        driveStatue_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ExtraOuterClass.Extra> extra_ =
        java.util.Collections.emptyList();
      private void ensureExtraIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          extra_ = new java.util.ArrayList<ExtraOuterClass.Extra>(extra_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ExtraOuterClass.Extra, ExtraOuterClass.Extra.Builder, ExtraOuterClass.ExtraOrBuilder> extraBuilder_;

      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public java.util.List<ExtraOuterClass.Extra> getExtraList() {
        if (extraBuilder_ == null) {
          return java.util.Collections.unmodifiableList(extra_);
        } else {
          return extraBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public int getExtraCount() {
        if (extraBuilder_ == null) {
          return extra_.size();
        } else {
          return extraBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra getExtra(int index) {
        if (extraBuilder_ == null) {
          return extra_.get(index);
        } else {
          return extraBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder setExtra(
          int index, ExtraOuterClass.Extra value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraIsMutable();
          extra_.set(index, value);
          onChanged();
        } else {
          extraBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder setExtra(
          int index, ExtraOuterClass.Extra.Builder builderForValue) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.set(index, builderForValue.build());
          onChanged();
        } else {
          extraBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(ExtraOuterClass.Extra value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraIsMutable();
          extra_.add(value);
          onChanged();
        } else {
          extraBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(
          int index, ExtraOuterClass.Extra value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraIsMutable();
          extra_.add(index, value);
          onChanged();
        } else {
          extraBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(
          ExtraOuterClass.Extra.Builder builderForValue) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.add(builderForValue.build());
          onChanged();
        } else {
          extraBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(
          int index, ExtraOuterClass.Extra.Builder builderForValue) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.add(index, builderForValue.build());
          onChanged();
        } else {
          extraBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addAllExtra(
          Iterable<? extends ExtraOuterClass.Extra> values) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, extra_);
          onChanged();
        } else {
          extraBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder clearExtra() {
        if (extraBuilder_ == null) {
          extra_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          extraBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder removeExtra(int index) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.remove(index);
          onChanged();
        } else {
          extraBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra.Builder getExtraBuilder(
          int index) {
        return getExtraFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.ExtraOrBuilder getExtraOrBuilder(
          int index) {
        if (extraBuilder_ == null) {
          return extra_.get(index);  } else {
          return extraBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public java.util.List<? extends ExtraOuterClass.ExtraOrBuilder>
           getExtraOrBuilderList() {
        if (extraBuilder_ != null) {
          return extraBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(extra_);
        }
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra.Builder addExtraBuilder() {
        return getExtraFieldBuilder().addBuilder(
            ExtraOuterClass.Extra.getDefaultInstance());
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra.Builder addExtraBuilder(
          int index) {
        return getExtraFieldBuilder().addBuilder(
            index, ExtraOuterClass.Extra.getDefaultInstance());
      }
      /**
       * <code>repeated .Extra extra = 2;</code>
       */
      public java.util.List<ExtraOuterClass.Extra.Builder>
           getExtraBuilderList() {
        return getExtraFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ExtraOuterClass.Extra, ExtraOuterClass.Extra.Builder, ExtraOuterClass.ExtraOrBuilder>
          getExtraFieldBuilder() {
        if (extraBuilder_ == null) {
          extraBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ExtraOuterClass.Extra, ExtraOuterClass.Extra.Builder, ExtraOuterClass.ExtraOrBuilder>(
                  extra_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          extra_ = null;
        }
        return extraBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DriveState)
    }

    // @@protoc_insertion_point(class_scope:DriveState)
    private static final DriveStateOuterClass.DriveState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DriveStateOuterClass.DriveState();
    }

    public static DriveStateOuterClass.DriveState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DriveState>
        PARSER = new com.google.protobuf.AbstractParser<DriveState>() {
      public DriveState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DriveState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DriveState> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DriveState> getParserForType() {
      return PARSER;
    }

    public DriveStateOuterClass.DriveState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DriveState_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DriveState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020DriveState.proto\032\013Extra.proto\"8\n\nDrive" +
      "State\022\023\n\013driveStatue\030\001 \001(\005\022\025\n\005extra\030\002 \003(" +
      "\0132\006.Extrab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ExtraOuterClass.getDescriptor(),
        }, assigner);
    internal_static_DriveState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DriveState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DriveState_descriptor,
        new String[] { "DriveStatue", "Extra", });
    ExtraOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
