package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreenWaveGuide.proto

public final class GreenWaveGuideOuterClass {
  private GreenWaveGuideOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GreenWaveGuideOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GreenWaveGuide)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
     * </pre>
     *
     * <code>.GreenWaveGuide.Direction driection = 1;</code>
     */
    int getDriectionValue();
    /**
     * <pre>
     *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
     * </pre>
     *
     * <code>.GreenWaveGuide.Direction driection = 1;</code>
     */
    GreenWaveGuideOuterClass.GreenWaveGuide.Direction getDriection();

    /**
     * <pre>
     *红绿灯状态
     * </pre>
     *
     * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
     */
    int getStatueValue();
    /**
     * <pre>
     *红绿灯状态
     * </pre>
     *
     * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
     */
    GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue getStatue();

    /**
     * <pre>
     *当前时间
     * </pre>
     *
     * <code>int32 time = 3;</code>
     */
    int getTime();

    /**
     * <pre>
     *建议最大速度
     * </pre>
     *
     * <code>int32 max = 4;</code>
     */
    int getMax();

    /**
     * <pre>
     *建议最小速度
     * </pre>
     *
     * <code>int32 min = 5;</code>
     */
    int getMin();

    /**
     * <pre>
     *红绿灯id,实际为红绿灯所在路口的id
     * </pre>
     *
     * <code>int32 id = 6;</code>
     */
    int getId();

    /**
     * <pre>
     *是否是当前车道的灯态
     * </pre>
     *
     * <code>bool isCurrent = 7;</code>
     */
    boolean getIsCurrent();
  }
  /**
   * <pre>
   *绿波引导
   * </pre>
   *
   * Protobuf type {@code GreenWaveGuide}
   */
  public  static final class GreenWaveGuide extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GreenWaveGuide)
      GreenWaveGuideOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GreenWaveGuide.newBuilder() to construct.
    private GreenWaveGuide(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GreenWaveGuide() {
      driection_ = 0;
      statue_ = 0;
      time_ = 0;
      max_ = 0;
      min_ = 0;
      id_ = 0;
      isCurrent_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GreenWaveGuide(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              driection_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              statue_ = rawValue;
              break;
            }
            case 24: {

              time_ = input.readInt32();
              break;
            }
            case 32: {

              max_ = input.readInt32();
              break;
            }
            case 40: {

              min_ = input.readInt32();
              break;
            }
            case 48: {

              id_ = input.readInt32();
              break;
            }
            case 56: {

              isCurrent_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GreenWaveGuideOuterClass.internal_static_GreenWaveGuide_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GreenWaveGuideOuterClass.internal_static_GreenWaveGuide_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GreenWaveGuideOuterClass.GreenWaveGuide.class, GreenWaveGuideOuterClass.GreenWaveGuide.Builder.class);
    }

    /**
     * <pre>
     *方向
     * </pre>
     *
     * Protobuf enum {@code GreenWaveGuide.Direction}
     */
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEFT = 0;</code>
       */
      LEFT(0),
      /**
       * <code>FRONT = 1;</code>
       */
      FRONT(1),
      /**
       * <code>RIGHT = 2;</code>
       */
      RIGHT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>LEFT = 0;</code>
       */
      public static final int LEFT_VALUE = 0;
      /**
       * <code>FRONT = 1;</code>
       */
      public static final int FRONT_VALUE = 1;
      /**
       * <code>RIGHT = 2;</code>
       */
      public static final int RIGHT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Direction valueOf(int value) {
        return forNumber(value);
      }

      public static Direction forNumber(int value) {
        switch (value) {
          case 0: return LEFT;
          case 1: return FRONT;
          case 2: return RIGHT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Direction> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return GreenWaveGuideOuterClass.GreenWaveGuide.getDescriptor().getEnumTypes().get(0);
      }

      private static final Direction[] VALUES = values();

      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Direction(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:GreenWaveGuide.Direction)
    }

    /**
     * <pre>
     *红绿灯状态
     * </pre>
     *
     * Protobuf enum {@code GreenWaveGuide.TrafficLightStatue}
     */
    public enum TrafficLightStatue
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>GREEN = 1;</code>
       */
      GREEN(1),
      /**
       * <code>YELLOW = 2;</code>
       */
      YELLOW(2),
      /**
       * <code>RED = 3;</code>
       */
      RED(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>GREEN = 1;</code>
       */
      public static final int GREEN_VALUE = 1;
      /**
       * <code>YELLOW = 2;</code>
       */
      public static final int YELLOW_VALUE = 2;
      /**
       * <code>RED = 3;</code>
       */
      public static final int RED_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TrafficLightStatue valueOf(int value) {
        return forNumber(value);
      }

      public static TrafficLightStatue forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return GREEN;
          case 2: return YELLOW;
          case 3: return RED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TrafficLightStatue>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TrafficLightStatue> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TrafficLightStatue>() {
              public TrafficLightStatue findValueByNumber(int number) {
                return TrafficLightStatue.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return GreenWaveGuideOuterClass.GreenWaveGuide.getDescriptor().getEnumTypes().get(1);
      }

      private static final TrafficLightStatue[] VALUES = values();

      public static TrafficLightStatue valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TrafficLightStatue(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:GreenWaveGuide.TrafficLightStatue)
    }

    public static final int DRIECTION_FIELD_NUMBER = 1;
    private int driection_;
    /**
     * <pre>
     *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
     * </pre>
     *
     * <code>.GreenWaveGuide.Direction driection = 1;</code>
     */
    public int getDriectionValue() {
      return driection_;
    }
    /**
     * <pre>
     *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
     * </pre>
     *
     * <code>.GreenWaveGuide.Direction driection = 1;</code>
     */
    public GreenWaveGuideOuterClass.GreenWaveGuide.Direction getDriection() {
      GreenWaveGuideOuterClass.GreenWaveGuide.Direction result = GreenWaveGuideOuterClass.GreenWaveGuide.Direction.valueOf(driection_);
      return result == null ? GreenWaveGuideOuterClass.GreenWaveGuide.Direction.UNRECOGNIZED : result;
    }

    public static final int STATUE_FIELD_NUMBER = 2;
    private int statue_;
    /**
     * <pre>
     *红绿灯状态
     * </pre>
     *
     * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
     */
    public int getStatueValue() {
      return statue_;
    }
    /**
     * <pre>
     *红绿灯状态
     * </pre>
     *
     * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
     */
    public GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue getStatue() {
      GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue result = GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue.valueOf(statue_);
      return result == null ? GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue.UNRECOGNIZED : result;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private int time_;
    /**
     * <pre>
     *当前时间
     * </pre>
     *
     * <code>int32 time = 3;</code>
     */
    public int getTime() {
      return time_;
    }

    public static final int MAX_FIELD_NUMBER = 4;
    private int max_;
    /**
     * <pre>
     *建议最大速度
     * </pre>
     *
     * <code>int32 max = 4;</code>
     */
    public int getMax() {
      return max_;
    }

    public static final int MIN_FIELD_NUMBER = 5;
    private int min_;
    /**
     * <pre>
     *建议最小速度
     * </pre>
     *
     * <code>int32 min = 5;</code>
     */
    public int getMin() {
      return min_;
    }

    public static final int ID_FIELD_NUMBER = 6;
    private int id_;
    /**
     * <pre>
     *红绿灯id,实际为红绿灯所在路口的id
     * </pre>
     *
     * <code>int32 id = 6;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ISCURRENT_FIELD_NUMBER = 7;
    private boolean isCurrent_;
    /**
     * <pre>
     *是否是当前车道的灯态
     * </pre>
     *
     * <code>bool isCurrent = 7;</code>
     */
    public boolean getIsCurrent() {
      return isCurrent_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (driection_ != GreenWaveGuideOuterClass.GreenWaveGuide.Direction.LEFT.getNumber()) {
        output.writeEnum(1, driection_);
      }
      if (statue_ != GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue.UNKNOWN.getNumber()) {
        output.writeEnum(2, statue_);
      }
      if (time_ != 0) {
        output.writeInt32(3, time_);
      }
      if (max_ != 0) {
        output.writeInt32(4, max_);
      }
      if (min_ != 0) {
        output.writeInt32(5, min_);
      }
      if (id_ != 0) {
        output.writeInt32(6, id_);
      }
      if (isCurrent_ != false) {
        output.writeBool(7, isCurrent_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (driection_ != GreenWaveGuideOuterClass.GreenWaveGuide.Direction.LEFT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, driection_);
      }
      if (statue_ != GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, statue_);
      }
      if (time_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, time_);
      }
      if (max_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, max_);
      }
      if (min_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, min_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, id_);
      }
      if (isCurrent_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isCurrent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GreenWaveGuideOuterClass.GreenWaveGuide)) {
        return super.equals(obj);
      }
      GreenWaveGuideOuterClass.GreenWaveGuide other = (GreenWaveGuideOuterClass.GreenWaveGuide) obj;

      boolean result = true;
      result = result && driection_ == other.driection_;
      result = result && statue_ == other.statue_;
      result = result && (getTime()
          == other.getTime());
      result = result && (getMax()
          == other.getMax());
      result = result && (getMin()
          == other.getMin());
      result = result && (getId()
          == other.getId());
      result = result && (getIsCurrent()
          == other.getIsCurrent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DRIECTION_FIELD_NUMBER;
      hash = (53 * hash) + driection_;
      hash = (37 * hash) + STATUE_FIELD_NUMBER;
      hash = (53 * hash) + statue_;
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime();
      hash = (37 * hash) + MAX_FIELD_NUMBER;
      hash = (53 * hash) + getMax();
      hash = (37 * hash) + MIN_FIELD_NUMBER;
      hash = (53 * hash) + getMin();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ISCURRENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsCurrent());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuide parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GreenWaveGuideOuterClass.GreenWaveGuide prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *绿波引导
     * </pre>
     *
     * Protobuf type {@code GreenWaveGuide}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GreenWaveGuide)
        GreenWaveGuideOuterClass.GreenWaveGuideOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GreenWaveGuideOuterClass.internal_static_GreenWaveGuide_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GreenWaveGuideOuterClass.internal_static_GreenWaveGuide_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GreenWaveGuideOuterClass.GreenWaveGuide.class, GreenWaveGuideOuterClass.GreenWaveGuide.Builder.class);
      }

      // Construct using GreenWaveGuideOuterClass.GreenWaveGuide.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        driection_ = 0;

        statue_ = 0;

        time_ = 0;

        max_ = 0;

        min_ = 0;

        id_ = 0;

        isCurrent_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GreenWaveGuideOuterClass.internal_static_GreenWaveGuide_descriptor;
      }

      public GreenWaveGuideOuterClass.GreenWaveGuide getDefaultInstanceForType() {
        return GreenWaveGuideOuterClass.GreenWaveGuide.getDefaultInstance();
      }

      public GreenWaveGuideOuterClass.GreenWaveGuide build() {
        GreenWaveGuideOuterClass.GreenWaveGuide result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GreenWaveGuideOuterClass.GreenWaveGuide buildPartial() {
        GreenWaveGuideOuterClass.GreenWaveGuide result = new GreenWaveGuideOuterClass.GreenWaveGuide(this);
        result.driection_ = driection_;
        result.statue_ = statue_;
        result.time_ = time_;
        result.max_ = max_;
        result.min_ = min_;
        result.id_ = id_;
        result.isCurrent_ = isCurrent_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GreenWaveGuideOuterClass.GreenWaveGuide) {
          return mergeFrom((GreenWaveGuideOuterClass.GreenWaveGuide)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GreenWaveGuideOuterClass.GreenWaveGuide other) {
        if (other == GreenWaveGuideOuterClass.GreenWaveGuide.getDefaultInstance()) return this;
        if (other.driection_ != 0) {
          setDriectionValue(other.getDriectionValue());
        }
        if (other.statue_ != 0) {
          setStatueValue(other.getStatueValue());
        }
        if (other.getTime() != 0) {
          setTime(other.getTime());
        }
        if (other.getMax() != 0) {
          setMax(other.getMax());
        }
        if (other.getMin() != 0) {
          setMin(other.getMin());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getIsCurrent() != false) {
          setIsCurrent(other.getIsCurrent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GreenWaveGuideOuterClass.GreenWaveGuide parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GreenWaveGuideOuterClass.GreenWaveGuide) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int driection_ = 0;
      /**
       * <pre>
       *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
       * </pre>
       *
       * <code>.GreenWaveGuide.Direction driection = 1;</code>
       */
      public int getDriectionValue() {
        return driection_;
      }
      /**
       * <pre>
       *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
       * </pre>
       *
       * <code>.GreenWaveGuide.Direction driection = 1;</code>
       */
      public Builder setDriectionValue(int value) {
        driection_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
       * </pre>
       *
       * <code>.GreenWaveGuide.Direction driection = 1;</code>
       */
      public GreenWaveGuideOuterClass.GreenWaveGuide.Direction getDriection() {
        GreenWaveGuideOuterClass.GreenWaveGuide.Direction result = GreenWaveGuideOuterClass.GreenWaveGuide.Direction.valueOf(driection_);
        return result == null ? GreenWaveGuideOuterClass.GreenWaveGuide.Direction.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
       * </pre>
       *
       * <code>.GreenWaveGuide.Direction driection = 1;</code>
       */
      public Builder setDriection(GreenWaveGuideOuterClass.GreenWaveGuide.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }

        driection_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车辆面对红绿灯,红绿灯所在的方位,即红绿灯在车辆 左/前/右
       * </pre>
       *
       * <code>.GreenWaveGuide.Direction driection = 1;</code>
       */
      public Builder clearDriection() {

        driection_ = 0;
        onChanged();
        return this;
      }

      private int statue_ = 0;
      /**
       * <pre>
       *红绿灯状态
       * </pre>
       *
       * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
       */
      public int getStatueValue() {
        return statue_;
      }
      /**
       * <pre>
       *红绿灯状态
       * </pre>
       *
       * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
       */
      public Builder setStatueValue(int value) {
        statue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *红绿灯状态
       * </pre>
       *
       * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
       */
      public GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue getStatue() {
        GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue result = GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue.valueOf(statue_);
        return result == null ? GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *红绿灯状态
       * </pre>
       *
       * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
       */
      public Builder setStatue(GreenWaveGuideOuterClass.GreenWaveGuide.TrafficLightStatue value) {
        if (value == null) {
          throw new NullPointerException();
        }

        statue_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *红绿灯状态
       * </pre>
       *
       * <code>.GreenWaveGuide.TrafficLightStatue statue = 2;</code>
       */
      public Builder clearStatue() {

        statue_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <pre>
       *当前时间
       * </pre>
       *
       * <code>int32 time = 3;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <pre>
       *当前时间
       * </pre>
       *
       * <code>int32 time = 3;</code>
       */
      public Builder setTime(int value) {

        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前时间
       * </pre>
       *
       * <code>int32 time = 3;</code>
       */
      public Builder clearTime() {

        time_ = 0;
        onChanged();
        return this;
      }

      private int max_ ;
      /**
       * <pre>
       *建议最大速度
       * </pre>
       *
       * <code>int32 max = 4;</code>
       */
      public int getMax() {
        return max_;
      }
      /**
       * <pre>
       *建议最大速度
       * </pre>
       *
       * <code>int32 max = 4;</code>
       */
      public Builder setMax(int value) {

        max_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *建议最大速度
       * </pre>
       *
       * <code>int32 max = 4;</code>
       */
      public Builder clearMax() {

        max_ = 0;
        onChanged();
        return this;
      }

      private int min_ ;
      /**
       * <pre>
       *建议最小速度
       * </pre>
       *
       * <code>int32 min = 5;</code>
       */
      public int getMin() {
        return min_;
      }
      /**
       * <pre>
       *建议最小速度
       * </pre>
       *
       * <code>int32 min = 5;</code>
       */
      public Builder setMin(int value) {

        min_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *建议最小速度
       * </pre>
       *
       * <code>int32 min = 5;</code>
       */
      public Builder clearMin() {

        min_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *红绿灯id,实际为红绿灯所在路口的id
       * </pre>
       *
       * <code>int32 id = 6;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *红绿灯id,实际为红绿灯所在路口的id
       * </pre>
       *
       * <code>int32 id = 6;</code>
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *红绿灯id,实际为红绿灯所在路口的id
       * </pre>
       *
       * <code>int32 id = 6;</code>
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private boolean isCurrent_ ;
      /**
       * <pre>
       *是否是当前车道的灯态
       * </pre>
       *
       * <code>bool isCurrent = 7;</code>
       */
      public boolean getIsCurrent() {
        return isCurrent_;
      }
      /**
       * <pre>
       *是否是当前车道的灯态
       * </pre>
       *
       * <code>bool isCurrent = 7;</code>
       */
      public Builder setIsCurrent(boolean value) {

        isCurrent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否是当前车道的灯态
       * </pre>
       *
       * <code>bool isCurrent = 7;</code>
       */
      public Builder clearIsCurrent() {

        isCurrent_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GreenWaveGuide)
    }

    // @@protoc_insertion_point(class_scope:GreenWaveGuide)
    private static final GreenWaveGuideOuterClass.GreenWaveGuide DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GreenWaveGuideOuterClass.GreenWaveGuide();
    }

    public static GreenWaveGuideOuterClass.GreenWaveGuide getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GreenWaveGuide>
        PARSER = new com.google.protobuf.AbstractParser<GreenWaveGuide>() {
      public GreenWaveGuide parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GreenWaveGuide(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GreenWaveGuide> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GreenWaveGuide> getParserForType() {
      return PARSER;
    }

    public GreenWaveGuideOuterClass.GreenWaveGuide getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GreenWaveGuideListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GreenWaveGuideList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    java.util.List<GreenWaveGuide>
        getGreenWaveGuideList();
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    GreenWaveGuideOuterClass.GreenWaveGuide getGreenWaveGuide(int index);
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    int getGreenWaveGuideCount();
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    java.util.List<? extends GreenWaveGuideOrBuilder>
        getGreenWaveGuideOrBuilderList();
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    GreenWaveGuideOuterClass.GreenWaveGuideOrBuilder getGreenWaveGuideOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GreenWaveGuideList}
   */
  public  static final class GreenWaveGuideList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GreenWaveGuideList)
      GreenWaveGuideListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GreenWaveGuideList.newBuilder() to construct.
    private GreenWaveGuideList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GreenWaveGuideList() {
      greenWaveGuide_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GreenWaveGuideList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                greenWaveGuide_ = new java.util.ArrayList<GreenWaveGuide>();
                mutable_bitField0_ |= 0x00000001;
              }
              greenWaveGuide_.add(
                  input.readMessage(GreenWaveGuideOuterClass.GreenWaveGuide.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          greenWaveGuide_ = java.util.Collections.unmodifiableList(greenWaveGuide_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GreenWaveGuideOuterClass.internal_static_GreenWaveGuideList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GreenWaveGuideOuterClass.internal_static_GreenWaveGuideList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GreenWaveGuideOuterClass.GreenWaveGuideList.class, GreenWaveGuideOuterClass.GreenWaveGuideList.Builder.class);
    }

    public static final int GREENWAVEGUIDE_FIELD_NUMBER = 1;
    private java.util.List<GreenWaveGuide> greenWaveGuide_;
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    public java.util.List<GreenWaveGuide> getGreenWaveGuideList() {
      return greenWaveGuide_;
    }
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    public java.util.List<? extends GreenWaveGuideOrBuilder>
        getGreenWaveGuideOrBuilderList() {
      return greenWaveGuide_;
    }
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    public int getGreenWaveGuideCount() {
      return greenWaveGuide_.size();
    }
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    public GreenWaveGuideOuterClass.GreenWaveGuide getGreenWaveGuide(int index) {
      return greenWaveGuide_.get(index);
    }
    /**
     * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
     */
    public GreenWaveGuideOuterClass.GreenWaveGuideOrBuilder getGreenWaveGuideOrBuilder(
        int index) {
      return greenWaveGuide_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < greenWaveGuide_.size(); i++) {
        output.writeMessage(1, greenWaveGuide_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < greenWaveGuide_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, greenWaveGuide_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GreenWaveGuideOuterClass.GreenWaveGuideList)) {
        return super.equals(obj);
      }
      GreenWaveGuideOuterClass.GreenWaveGuideList other = (GreenWaveGuideOuterClass.GreenWaveGuideList) obj;

      boolean result = true;
      result = result && getGreenWaveGuideList()
          .equals(other.getGreenWaveGuideList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGreenWaveGuideCount() > 0) {
        hash = (37 * hash) + GREENWAVEGUIDE_FIELD_NUMBER;
        hash = (53 * hash) + getGreenWaveGuideList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GreenWaveGuideOuterClass.GreenWaveGuideList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GreenWaveGuideOuterClass.GreenWaveGuideList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GreenWaveGuideList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GreenWaveGuideList)
        GreenWaveGuideOuterClass.GreenWaveGuideListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GreenWaveGuideOuterClass.internal_static_GreenWaveGuideList_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GreenWaveGuideOuterClass.internal_static_GreenWaveGuideList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GreenWaveGuideOuterClass.GreenWaveGuideList.class, GreenWaveGuideOuterClass.GreenWaveGuideList.Builder.class);
      }

      // Construct using GreenWaveGuideOuterClass.GreenWaveGuideList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGreenWaveGuideFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (greenWaveGuideBuilder_ == null) {
          greenWaveGuide_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          greenWaveGuideBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GreenWaveGuideOuterClass.internal_static_GreenWaveGuideList_descriptor;
      }

      public GreenWaveGuideOuterClass.GreenWaveGuideList getDefaultInstanceForType() {
        return GreenWaveGuideOuterClass.GreenWaveGuideList.getDefaultInstance();
      }

      public GreenWaveGuideOuterClass.GreenWaveGuideList build() {
        GreenWaveGuideOuterClass.GreenWaveGuideList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GreenWaveGuideOuterClass.GreenWaveGuideList buildPartial() {
        GreenWaveGuideOuterClass.GreenWaveGuideList result = new GreenWaveGuideOuterClass.GreenWaveGuideList(this);
        int from_bitField0_ = bitField0_;
        if (greenWaveGuideBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            greenWaveGuide_ = java.util.Collections.unmodifiableList(greenWaveGuide_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.greenWaveGuide_ = greenWaveGuide_;
        } else {
          result.greenWaveGuide_ = greenWaveGuideBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GreenWaveGuideOuterClass.GreenWaveGuideList) {
          return mergeFrom((GreenWaveGuideOuterClass.GreenWaveGuideList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GreenWaveGuideOuterClass.GreenWaveGuideList other) {
        if (other == GreenWaveGuideOuterClass.GreenWaveGuideList.getDefaultInstance()) return this;
        if (greenWaveGuideBuilder_ == null) {
          if (!other.greenWaveGuide_.isEmpty()) {
            if (greenWaveGuide_.isEmpty()) {
              greenWaveGuide_ = other.greenWaveGuide_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGreenWaveGuideIsMutable();
              greenWaveGuide_.addAll(other.greenWaveGuide_);
            }
            onChanged();
          }
        } else {
          if (!other.greenWaveGuide_.isEmpty()) {
            if (greenWaveGuideBuilder_.isEmpty()) {
              greenWaveGuideBuilder_.dispose();
              greenWaveGuideBuilder_ = null;
              greenWaveGuide_ = other.greenWaveGuide_;
              bitField0_ = (bitField0_ & ~0x00000001);
              greenWaveGuideBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGreenWaveGuideFieldBuilder() : null;
            } else {
              greenWaveGuideBuilder_.addAllMessages(other.greenWaveGuide_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GreenWaveGuideOuterClass.GreenWaveGuideList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GreenWaveGuideOuterClass.GreenWaveGuideList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<GreenWaveGuide> greenWaveGuide_ =
        java.util.Collections.emptyList();
      private void ensureGreenWaveGuideIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          greenWaveGuide_ = new java.util.ArrayList<GreenWaveGuide>(greenWaveGuide_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GreenWaveGuide, GreenWaveGuide.Builder, GreenWaveGuideOrBuilder> greenWaveGuideBuilder_;

      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public java.util.List<GreenWaveGuide> getGreenWaveGuideList() {
        if (greenWaveGuideBuilder_ == null) {
          return java.util.Collections.unmodifiableList(greenWaveGuide_);
        } else {
          return greenWaveGuideBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public int getGreenWaveGuideCount() {
        if (greenWaveGuideBuilder_ == null) {
          return greenWaveGuide_.size();
        } else {
          return greenWaveGuideBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public GreenWaveGuideOuterClass.GreenWaveGuide getGreenWaveGuide(int index) {
        if (greenWaveGuideBuilder_ == null) {
          return greenWaveGuide_.get(index);
        } else {
          return greenWaveGuideBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder setGreenWaveGuide(
          int index, GreenWaveGuideOuterClass.GreenWaveGuide value) {
        if (greenWaveGuideBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGreenWaveGuideIsMutable();
          greenWaveGuide_.set(index, value);
          onChanged();
        } else {
          greenWaveGuideBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder setGreenWaveGuide(
          int index, GreenWaveGuideOuterClass.GreenWaveGuide.Builder builderForValue) {
        if (greenWaveGuideBuilder_ == null) {
          ensureGreenWaveGuideIsMutable();
          greenWaveGuide_.set(index, builderForValue.build());
          onChanged();
        } else {
          greenWaveGuideBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder addGreenWaveGuide(GreenWaveGuideOuterClass.GreenWaveGuide value) {
        if (greenWaveGuideBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGreenWaveGuideIsMutable();
          greenWaveGuide_.add(value);
          onChanged();
        } else {
          greenWaveGuideBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder addGreenWaveGuide(
          int index, GreenWaveGuideOuterClass.GreenWaveGuide value) {
        if (greenWaveGuideBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGreenWaveGuideIsMutable();
          greenWaveGuide_.add(index, value);
          onChanged();
        } else {
          greenWaveGuideBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder addGreenWaveGuide(
          GreenWaveGuideOuterClass.GreenWaveGuide.Builder builderForValue) {
        if (greenWaveGuideBuilder_ == null) {
          ensureGreenWaveGuideIsMutable();
          greenWaveGuide_.add(builderForValue.build());
          onChanged();
        } else {
          greenWaveGuideBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder addGreenWaveGuide(
          int index, GreenWaveGuideOuterClass.GreenWaveGuide.Builder builderForValue) {
        if (greenWaveGuideBuilder_ == null) {
          ensureGreenWaveGuideIsMutable();
          greenWaveGuide_.add(index, builderForValue.build());
          onChanged();
        } else {
          greenWaveGuideBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder addAllGreenWaveGuide(
          Iterable<? extends GreenWaveGuide> values) {
        if (greenWaveGuideBuilder_ == null) {
          ensureGreenWaveGuideIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, greenWaveGuide_);
          onChanged();
        } else {
          greenWaveGuideBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder clearGreenWaveGuide() {
        if (greenWaveGuideBuilder_ == null) {
          greenWaveGuide_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          greenWaveGuideBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public Builder removeGreenWaveGuide(int index) {
        if (greenWaveGuideBuilder_ == null) {
          ensureGreenWaveGuideIsMutable();
          greenWaveGuide_.remove(index);
          onChanged();
        } else {
          greenWaveGuideBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public GreenWaveGuideOuterClass.GreenWaveGuide.Builder getGreenWaveGuideBuilder(
          int index) {
        return getGreenWaveGuideFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public GreenWaveGuideOuterClass.GreenWaveGuideOrBuilder getGreenWaveGuideOrBuilder(
          int index) {
        if (greenWaveGuideBuilder_ == null) {
          return greenWaveGuide_.get(index);  } else {
          return greenWaveGuideBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public java.util.List<? extends GreenWaveGuideOrBuilder>
           getGreenWaveGuideOrBuilderList() {
        if (greenWaveGuideBuilder_ != null) {
          return greenWaveGuideBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(greenWaveGuide_);
        }
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public GreenWaveGuideOuterClass.GreenWaveGuide.Builder addGreenWaveGuideBuilder() {
        return getGreenWaveGuideFieldBuilder().addBuilder(
            GreenWaveGuideOuterClass.GreenWaveGuide.getDefaultInstance());
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public GreenWaveGuideOuterClass.GreenWaveGuide.Builder addGreenWaveGuideBuilder(
          int index) {
        return getGreenWaveGuideFieldBuilder().addBuilder(
            index, GreenWaveGuideOuterClass.GreenWaveGuide.getDefaultInstance());
      }
      /**
       * <code>repeated .GreenWaveGuide greenWaveGuide = 1;</code>
       */
      public java.util.List<GreenWaveGuide.Builder>
           getGreenWaveGuideBuilderList() {
        return getGreenWaveGuideFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GreenWaveGuide, GreenWaveGuide.Builder, GreenWaveGuideOrBuilder>
          getGreenWaveGuideFieldBuilder() {
        if (greenWaveGuideBuilder_ == null) {
          greenWaveGuideBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GreenWaveGuide, GreenWaveGuide.Builder, GreenWaveGuideOrBuilder>(
                  greenWaveGuide_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          greenWaveGuide_ = null;
        }
        return greenWaveGuideBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GreenWaveGuideList)
    }

    // @@protoc_insertion_point(class_scope:GreenWaveGuideList)
    private static final GreenWaveGuideOuterClass.GreenWaveGuideList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GreenWaveGuideOuterClass.GreenWaveGuideList();
    }

    public static GreenWaveGuideOuterClass.GreenWaveGuideList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GreenWaveGuideList>
        PARSER = new com.google.protobuf.AbstractParser<GreenWaveGuideList>() {
      public GreenWaveGuideList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GreenWaveGuideList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GreenWaveGuideList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GreenWaveGuideList> getParserForType() {
      return PARSER;
    }

    public GreenWaveGuideOuterClass.GreenWaveGuideList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GreenWaveGuide_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreenWaveGuide_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GreenWaveGuideList_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreenWaveGuideList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024GreenWaveGuide.proto\"\251\002\n\016GreenWaveGuid" +
      "e\022,\n\tdriection\030\001 \001(\0162\031.GreenWaveGuide.Di" +
      "rection\0222\n\006statue\030\002 \001(\0162\".GreenWaveGuide" +
      ".TrafficLightStatue\022\014\n\004time\030\003 \001(\005\022\013\n\003max" +
      "\030\004 \001(\005\022\013\n\003min\030\005 \001(\005\022\n\n\002id\030\006 \001(\005\022\021\n\tisCur" +
      "rent\030\007 \001(\010\"+\n\tDirection\022\010\n\004LEFT\020\000\022\t\n\005FRO" +
      "NT\020\001\022\t\n\005RIGHT\020\002\"A\n\022TrafficLightStatue\022\013\n" +
      "\007UNKNOWN\020\000\022\t\n\005GREEN\020\001\022\n\n\006YELLOW\020\002\022\007\n\003RED" +
      "\020\003\"=\n\022GreenWaveGuideList\022\'\n\016greenWaveGui" +
      "de\030\001 \003(\0132\017.GreenWaveGuideb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GreenWaveGuide_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GreenWaveGuide_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GreenWaveGuide_descriptor,
        new String[] { "Driection", "Statue", "Time", "Max", "Min", "Id", "IsCurrent", });
    internal_static_GreenWaveGuideList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GreenWaveGuideList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GreenWaveGuideList_descriptor,
        new String[] { "GreenWaveGuide", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
