package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guidepost.proto

public final class GuidepostOuterClass {
  private GuidepostOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GuidepostOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Guidepost)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *路牌类型
     * </pre>
     *
     * <code>.Guidepost.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *路牌类型
     * </pre>
     *
     * <code>.Guidepost.Type type = 1;</code>
     */
    GuidepostOuterClass.Guidepost.Type getType();

    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    java.util.List<ExtraOuterClass.Extra>
        getExtraList();
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    ExtraOuterClass.Extra getExtra(int index);
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    int getExtraCount();
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    java.util.List<? extends ExtraOuterClass.ExtraOrBuilder>
        getExtraOrBuilderList();
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    ExtraOuterClass.ExtraOrBuilder getExtraOrBuilder(
            int index);
  }
  /**
   * <pre>
   *路牌信息
   * </pre>
   *
   * Protobuf type {@code Guidepost}
   */
  public  static final class Guidepost extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Guidepost)
      GuidepostOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Guidepost.newBuilder() to construct.
    private Guidepost(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Guidepost() {
      type_ = 0;
      extra_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Guidepost(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                extra_ = new java.util.ArrayList<ExtraOuterClass.Extra>();
                mutable_bitField0_ |= 0x00000002;
              }
              extra_.add(
                  input.readMessage(ExtraOuterClass.Extra.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          extra_ = java.util.Collections.unmodifiableList(extra_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GuidepostOuterClass.internal_static_Guidepost_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GuidepostOuterClass.internal_static_Guidepost_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GuidepostOuterClass.Guidepost.class, GuidepostOuterClass.Guidepost.Builder.class);
    }

    /**
     * Protobuf enum {@code Guidepost.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *限速
       * </pre>
       *
       * <code>SPEED_LIMIT = 0;</code>
       */
      SPEED_LIMIT(0),
      /**
       * <pre>
       *道路施工
       * </pre>
       *
       * <code>ROAD_WORKS = 1;</code>
       */
      ROAD_WORKS(1),
      /**
       * <pre>
       *危险预警
       * </pre>
       *
       * <code>DANGEROUS = 2;</code>
       */
      DANGEROUS(2),
      /**
       * <pre>
       * 减速让行
       * </pre>
       *
       * <code>SLOW_DOWN_TO_GIVE_WAY = 3;</code>
       */
      SLOW_DOWN_TO_GIVE_WAY(3),
      /**
       * <pre>
       *注意儿童
       * </pre>
       *
       * <code>WATCH_FOR_CHILDREN = 4;</code>
       */
      WATCH_FOR_CHILDREN(4),
      /**
       * <pre>
       *禁止停车
       * </pre>
       *
       * <code>NO_PARKING = 5;</code>
       */
      NO_PARKING(5),
      /**
       * <pre>
       *国标交通部消息类型
       * </pre>
       *
       * <code>JD_TRAFFIC_INCIDENTS = 6;</code>
       */
      JD_TRAFFIC_INCIDENTS(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *限速
       * </pre>
       *
       * <code>SPEED_LIMIT = 0;</code>
       */
      public static final int SPEED_LIMIT_VALUE = 0;
      /**
       * <pre>
       *道路施工
       * </pre>
       *
       * <code>ROAD_WORKS = 1;</code>
       */
      public static final int ROAD_WORKS_VALUE = 1;
      /**
       * <pre>
       *危险预警
       * </pre>
       *
       * <code>DANGEROUS = 2;</code>
       */
      public static final int DANGEROUS_VALUE = 2;
      /**
       * <pre>
       * 减速让行
       * </pre>
       *
       * <code>SLOW_DOWN_TO_GIVE_WAY = 3;</code>
       */
      public static final int SLOW_DOWN_TO_GIVE_WAY_VALUE = 3;
      /**
       * <pre>
       *注意儿童
       * </pre>
       *
       * <code>WATCH_FOR_CHILDREN = 4;</code>
       */
      public static final int WATCH_FOR_CHILDREN_VALUE = 4;
      /**
       * <pre>
       *禁止停车
       * </pre>
       *
       * <code>NO_PARKING = 5;</code>
       */
      public static final int NO_PARKING_VALUE = 5;
      /**
       * <pre>
       *国标交通部消息类型
       * </pre>
       *
       * <code>JD_TRAFFIC_INCIDENTS = 6;</code>
       */
      public static final int JD_TRAFFIC_INCIDENTS_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return SPEED_LIMIT;
          case 1: return ROAD_WORKS;
          case 2: return DANGEROUS;
          case 3: return SLOW_DOWN_TO_GIVE_WAY;
          case 4: return WATCH_FOR_CHILDREN;
          case 5: return NO_PARKING;
          case 6: return JD_TRAFFIC_INCIDENTS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return GuidepostOuterClass.Guidepost.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Guidepost.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *路牌类型
     * </pre>
     *
     * <code>.Guidepost.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *路牌类型
     * </pre>
     *
     * <code>.Guidepost.Type type = 1;</code>
     */
    public GuidepostOuterClass.Guidepost.Type getType() {
      GuidepostOuterClass.Guidepost.Type result = GuidepostOuterClass.Guidepost.Type.valueOf(type_);
      return result == null ? GuidepostOuterClass.Guidepost.Type.UNRECOGNIZED : result;
    }

    public static final int EXTRA_FIELD_NUMBER = 2;
    private java.util.List<ExtraOuterClass.Extra> extra_;
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    public java.util.List<ExtraOuterClass.Extra> getExtraList() {
      return extra_;
    }
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    public java.util.List<? extends ExtraOuterClass.ExtraOrBuilder>
        getExtraOrBuilderList() {
      return extra_;
    }
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    public int getExtraCount() {
      return extra_.size();
    }
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    public ExtraOuterClass.Extra getExtra(int index) {
      return extra_.get(index);
    }
    /**
     * <pre>
     *附加的参数信息,比如限速,限速信息可以从这里获取
     * </pre>
     *
     * <code>repeated .Extra extra = 2;</code>
     */
    public ExtraOuterClass.ExtraOrBuilder getExtraOrBuilder(
        int index) {
      return extra_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != GuidepostOuterClass.Guidepost.Type.SPEED_LIMIT.getNumber()) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < extra_.size(); i++) {
        output.writeMessage(2, extra_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != GuidepostOuterClass.Guidepost.Type.SPEED_LIMIT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      for (int i = 0; i < extra_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, extra_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GuidepostOuterClass.Guidepost)) {
        return super.equals(obj);
      }
      GuidepostOuterClass.Guidepost other = (GuidepostOuterClass.Guidepost) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getExtraList()
          .equals(other.getExtraList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getExtraCount() > 0) {
        hash = (37 * hash) + EXTRA_FIELD_NUMBER;
        hash = (53 * hash) + getExtraList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GuidepostOuterClass.Guidepost parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GuidepostOuterClass.Guidepost parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GuidepostOuterClass.Guidepost parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GuidepostOuterClass.Guidepost parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GuidepostOuterClass.Guidepost prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *路牌信息
     * </pre>
     *
     * Protobuf type {@code Guidepost}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Guidepost)
        GuidepostOuterClass.GuidepostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GuidepostOuterClass.internal_static_Guidepost_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GuidepostOuterClass.internal_static_Guidepost_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GuidepostOuterClass.Guidepost.class, GuidepostOuterClass.Guidepost.Builder.class);
      }

      // Construct using GuidepostOuterClass.Guidepost.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExtraFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (extraBuilder_ == null) {
          extra_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          extraBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GuidepostOuterClass.internal_static_Guidepost_descriptor;
      }

      public GuidepostOuterClass.Guidepost getDefaultInstanceForType() {
        return GuidepostOuterClass.Guidepost.getDefaultInstance();
      }

      public GuidepostOuterClass.Guidepost build() {
        GuidepostOuterClass.Guidepost result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GuidepostOuterClass.Guidepost buildPartial() {
        GuidepostOuterClass.Guidepost result = new GuidepostOuterClass.Guidepost(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (extraBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            extra_ = java.util.Collections.unmodifiableList(extra_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.extra_ = extra_;
        } else {
          result.extra_ = extraBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GuidepostOuterClass.Guidepost) {
          return mergeFrom((GuidepostOuterClass.Guidepost)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GuidepostOuterClass.Guidepost other) {
        if (other == GuidepostOuterClass.Guidepost.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (extraBuilder_ == null) {
          if (!other.extra_.isEmpty()) {
            if (extra_.isEmpty()) {
              extra_ = other.extra_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureExtraIsMutable();
              extra_.addAll(other.extra_);
            }
            onChanged();
          }
        } else {
          if (!other.extra_.isEmpty()) {
            if (extraBuilder_.isEmpty()) {
              extraBuilder_.dispose();
              extraBuilder_ = null;
              extra_ = other.extra_;
              bitField0_ = (bitField0_ & ~0x00000002);
              extraBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExtraFieldBuilder() : null;
            } else {
              extraBuilder_.addAllMessages(other.extra_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GuidepostOuterClass.Guidepost parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GuidepostOuterClass.Guidepost) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       *路牌类型
       * </pre>
       *
       * <code>.Guidepost.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *路牌类型
       * </pre>
       *
       * <code>.Guidepost.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *路牌类型
       * </pre>
       *
       * <code>.Guidepost.Type type = 1;</code>
       */
      public GuidepostOuterClass.Guidepost.Type getType() {
        GuidepostOuterClass.Guidepost.Type result = GuidepostOuterClass.Guidepost.Type.valueOf(type_);
        return result == null ? GuidepostOuterClass.Guidepost.Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *路牌类型
       * </pre>
       *
       * <code>.Guidepost.Type type = 1;</code>
       */
      public Builder setType(GuidepostOuterClass.Guidepost.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }

        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *路牌类型
       * </pre>
       *
       * <code>.Guidepost.Type type = 1;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ExtraOuterClass.Extra> extra_ =
        java.util.Collections.emptyList();
      private void ensureExtraIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          extra_ = new java.util.ArrayList<ExtraOuterClass.Extra>(extra_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ExtraOuterClass.Extra, ExtraOuterClass.Extra.Builder, ExtraOuterClass.ExtraOrBuilder> extraBuilder_;

      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public java.util.List<ExtraOuterClass.Extra> getExtraList() {
        if (extraBuilder_ == null) {
          return java.util.Collections.unmodifiableList(extra_);
        } else {
          return extraBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public int getExtraCount() {
        if (extraBuilder_ == null) {
          return extra_.size();
        } else {
          return extraBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra getExtra(int index) {
        if (extraBuilder_ == null) {
          return extra_.get(index);
        } else {
          return extraBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder setExtra(
          int index, ExtraOuterClass.Extra value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraIsMutable();
          extra_.set(index, value);
          onChanged();
        } else {
          extraBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder setExtra(
          int index, ExtraOuterClass.Extra.Builder builderForValue) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.set(index, builderForValue.build());
          onChanged();
        } else {
          extraBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(ExtraOuterClass.Extra value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraIsMutable();
          extra_.add(value);
          onChanged();
        } else {
          extraBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(
          int index, ExtraOuterClass.Extra value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtraIsMutable();
          extra_.add(index, value);
          onChanged();
        } else {
          extraBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(
          ExtraOuterClass.Extra.Builder builderForValue) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.add(builderForValue.build());
          onChanged();
        } else {
          extraBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addExtra(
          int index, ExtraOuterClass.Extra.Builder builderForValue) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.add(index, builderForValue.build());
          onChanged();
        } else {
          extraBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder addAllExtra(
          Iterable<? extends ExtraOuterClass.Extra> values) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, extra_);
          onChanged();
        } else {
          extraBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder clearExtra() {
        if (extraBuilder_ == null) {
          extra_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          extraBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public Builder removeExtra(int index) {
        if (extraBuilder_ == null) {
          ensureExtraIsMutable();
          extra_.remove(index);
          onChanged();
        } else {
          extraBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra.Builder getExtraBuilder(
          int index) {
        return getExtraFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.ExtraOrBuilder getExtraOrBuilder(
          int index) {
        if (extraBuilder_ == null) {
          return extra_.get(index);  } else {
          return extraBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public java.util.List<? extends ExtraOuterClass.ExtraOrBuilder>
           getExtraOrBuilderList() {
        if (extraBuilder_ != null) {
          return extraBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(extra_);
        }
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra.Builder addExtraBuilder() {
        return getExtraFieldBuilder().addBuilder(
            ExtraOuterClass.Extra.getDefaultInstance());
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public ExtraOuterClass.Extra.Builder addExtraBuilder(
          int index) {
        return getExtraFieldBuilder().addBuilder(
            index, ExtraOuterClass.Extra.getDefaultInstance());
      }
      /**
       * <pre>
       *附加的参数信息,比如限速,限速信息可以从这里获取
       * </pre>
       *
       * <code>repeated .Extra extra = 2;</code>
       */
      public java.util.List<ExtraOuterClass.Extra.Builder>
           getExtraBuilderList() {
        return getExtraFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ExtraOuterClass.Extra, ExtraOuterClass.Extra.Builder, ExtraOuterClass.ExtraOrBuilder>
          getExtraFieldBuilder() {
        if (extraBuilder_ == null) {
          extraBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ExtraOuterClass.Extra, ExtraOuterClass.Extra.Builder, ExtraOuterClass.ExtraOrBuilder>(
                  extra_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          extra_ = null;
        }
        return extraBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Guidepost)
    }

    // @@protoc_insertion_point(class_scope:Guidepost)
    private static final GuidepostOuterClass.Guidepost DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GuidepostOuterClass.Guidepost();
    }

    public static GuidepostOuterClass.Guidepost getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Guidepost>
        PARSER = new com.google.protobuf.AbstractParser<Guidepost>() {
      public Guidepost parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Guidepost(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Guidepost> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Guidepost> getParserForType() {
      return PARSER;
    }

    public GuidepostOuterClass.Guidepost getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Guidepost_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Guidepost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017Guidepost.proto\032\013Extra.proto\"\327\001\n\tGuide" +
      "post\022\035\n\004type\030\001 \001(\0162\017.Guidepost.Type\022\025\n\005e" +
      "xtra\030\002 \003(\0132\006.Extra\"\223\001\n\004Type\022\017\n\013SPEED_LIM" +
      "IT\020\000\022\016\n\nROAD_WORKS\020\001\022\r\n\tDANGEROUS\020\002\022\031\n\025S" +
      "LOW_DOWN_TO_GIVE_WAY\020\003\022\026\n\022WATCH_FOR_CHIL" +
      "DREN\020\004\022\016\n\nNO_PARKING\020\005\022\030\n\024JD_TRAFFIC_INC" +
      "IDENTS\020\006b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ExtraOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Guidepost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Guidepost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Guidepost_descriptor,
        new String[] { "Type", "Extra", });
    ExtraOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
