package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Head.proto

public final class HeadOuterClass {
  private HeadOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Head)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 0: OBU 1：RSU
     * </pre>
     *
     * <code>uint32 deviceType = 1;</code>
     */
    int getDeviceType();

    /**
     * <pre>
     * 车牌号
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    String getDeviceId();
    /**
     * <pre>
     * 车牌号
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     * utc 时间戳 单位：毫秒
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     * 协议版本 2.0
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    String getVersion();
    /**
     * <pre>
     * 协议版本 2.0
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     * OBU通信模式 1、PC5 2、EUHT 3、PC5 &amp; EUHT 4、未知
     * </pre>
     *
     * <code>int32 communicationMode = 5;</code>
     */
    int getCommunicationMode();
  }
  /**
   * Protobuf type {@code Head}
   */
  public  static final class Head extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Head)
      HeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Head.newBuilder() to construct.
    private Head(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Head() {
      deviceType_ = 0;
      deviceId_ = "";
      timestamp_ = 0L;
      version_ = "";
      communicationMode_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Head(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              deviceType_ = input.readUInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 24: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 40: {

              communicationMode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeadOuterClass.internal_static_Head_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeadOuterClass.internal_static_Head_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeadOuterClass.Head.class, HeadOuterClass.Head.Builder.class);
    }

    public static final int DEVICETYPE_FIELD_NUMBER = 1;
    private int deviceType_;
    /**
     * <pre>
     * 0: OBU 1：RSU
     * </pre>
     *
     * <code>uint32 deviceType = 1;</code>
     */
    public int getDeviceType() {
      return deviceType_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 2;
    private volatile Object deviceId_;
    /**
     * <pre>
     * 车牌号
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 车牌号
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <pre>
     * utc 时间戳 单位：毫秒
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private volatile Object version_;
    /**
     * <pre>
     * 协议版本 2.0
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 协议版本 2.0
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMUNICATIONMODE_FIELD_NUMBER = 5;
    private int communicationMode_;
    /**
     * <pre>
     * OBU通信模式 1、PC5 2、EUHT 3、PC5 &amp; EUHT 4、未知
     * </pre>
     *
     * <code>int32 communicationMode = 5;</code>
     */
    public int getCommunicationMode() {
      return communicationMode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deviceType_ != 0) {
        output.writeUInt32(1, deviceType_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(3, timestamp_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
      }
      if (communicationMode_ != 0) {
        output.writeInt32(5, communicationMode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deviceType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, deviceType_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
      }
      if (communicationMode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, communicationMode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HeadOuterClass.Head)) {
        return super.equals(obj);
      }
      HeadOuterClass.Head other = (HeadOuterClass.Head) obj;

      boolean result = true;
      result = result && (getDeviceType()
          == other.getDeviceType());
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (getCommunicationMode()
          == other.getCommunicationMode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceType();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + COMMUNICATIONMODE_FIELD_NUMBER;
      hash = (53 * hash) + getCommunicationMode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HeadOuterClass.Head parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeadOuterClass.Head parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeadOuterClass.Head parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeadOuterClass.Head parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeadOuterClass.Head parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeadOuterClass.Head parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeadOuterClass.Head parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeadOuterClass.Head parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeadOuterClass.Head parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HeadOuterClass.Head parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HeadOuterClass.Head parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HeadOuterClass.Head parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HeadOuterClass.Head prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Head}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Head)
        HeadOuterClass.HeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeadOuterClass.internal_static_Head_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeadOuterClass.internal_static_Head_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeadOuterClass.Head.class, HeadOuterClass.Head.Builder.class);
      }

      // Construct using HeadOuterClass.Head.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceType_ = 0;

        deviceId_ = "";

        timestamp_ = 0L;

        version_ = "";

        communicationMode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeadOuterClass.internal_static_Head_descriptor;
      }

      public HeadOuterClass.Head getDefaultInstanceForType() {
        return HeadOuterClass.Head.getDefaultInstance();
      }

      public HeadOuterClass.Head build() {
        HeadOuterClass.Head result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeadOuterClass.Head buildPartial() {
        HeadOuterClass.Head result = new HeadOuterClass.Head(this);
        result.deviceType_ = deviceType_;
        result.deviceId_ = deviceId_;
        result.timestamp_ = timestamp_;
        result.version_ = version_;
        result.communicationMode_ = communicationMode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeadOuterClass.Head) {
          return mergeFrom((HeadOuterClass.Head)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeadOuterClass.Head other) {
        if (other == HeadOuterClass.Head.getDefaultInstance()) return this;
        if (other.getDeviceType() != 0) {
          setDeviceType(other.getDeviceType());
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getCommunicationMode() != 0) {
          setCommunicationMode(other.getCommunicationMode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeadOuterClass.Head parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeadOuterClass.Head) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int deviceType_ ;
      /**
       * <pre>
       * 0: OBU 1：RSU
       * </pre>
       *
       * <code>uint32 deviceType = 1;</code>
       */
      public int getDeviceType() {
        return deviceType_;
      }
      /**
       * <pre>
       * 0: OBU 1：RSU
       * </pre>
       *
       * <code>uint32 deviceType = 1;</code>
       */
      public Builder setDeviceType(int value) {

        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0: OBU 1：RSU
       * </pre>
       *
       * <code>uint32 deviceType = 1;</code>
       */
      public Builder clearDeviceType() {

        deviceType_ = 0;
        onChanged();
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <pre>
       * 车牌号
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 车牌号
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 车牌号
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车牌号
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public Builder clearDeviceId() {

        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车牌号
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        deviceId_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * utc 时间戳 单位：毫秒
       * </pre>
       *
       * <code>uint64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * utc 时间戳 单位：毫秒
       * </pre>
       *
       * <code>uint64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utc 时间戳 单位：毫秒
       * </pre>
       *
       * <code>uint64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {

        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <pre>
       * 协议版本 2.0
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 协议版本 2.0
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 协议版本 2.0
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议版本 2.0
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public Builder clearVersion() {

        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议版本 2.0
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        version_ = value;
        onChanged();
        return this;
      }

      private int communicationMode_ ;
      /**
       * <pre>
       * OBU通信模式 1、PC5 2、EUHT 3、PC5 &amp; EUHT 4、未知
       * </pre>
       *
       * <code>int32 communicationMode = 5;</code>
       */
      public int getCommunicationMode() {
        return communicationMode_;
      }
      /**
       * <pre>
       * OBU通信模式 1、PC5 2、EUHT 3、PC5 &amp; EUHT 4、未知
       * </pre>
       *
       * <code>int32 communicationMode = 5;</code>
       */
      public Builder setCommunicationMode(int value) {

        communicationMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * OBU通信模式 1、PC5 2、EUHT 3、PC5 &amp; EUHT 4、未知
       * </pre>
       *
       * <code>int32 communicationMode = 5;</code>
       */
      public Builder clearCommunicationMode() {

        communicationMode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Head)
    }

    // @@protoc_insertion_point(class_scope:Head)
    private static final HeadOuterClass.Head DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HeadOuterClass.Head();
    }

    public static HeadOuterClass.Head getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Head>
        PARSER = new com.google.protobuf.AbstractParser<Head>() {
      public Head parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Head(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Head> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Head> getParserForType() {
      return PARSER;
    }

    public HeadOuterClass.Head getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Head_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Head_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nHead.proto\"k\n\004Head\022\022\n\ndeviceType\030\001 \001(\r" +
      "\022\020\n\010deviceId\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\004\022\017\n" +
      "\007version\030\004 \001(\t\022\031\n\021communicationMode\030\005 \001(" +
      "\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Head_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Head_descriptor,
        new String[] { "DeviceType", "DeviceId", "Timestamp", "Version", "CommunicationMode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
