package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Icdc2Hmi.proto

public final class Icdc2HmiOuterClass {
  private Icdc2HmiOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Icdc2HmiOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Icdc2Hmi)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Head head = 1;</code>
     */
    boolean hasHead();
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Head head = 1;</code>
     */
    HeadOuterClass.Head getHead();
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Head head = 1;</code>
     */
    HeadOuterClass.HeadOrBuilder getHeadOrBuilder();

    /**
     * <pre>
     * HMI消息
     * </pre>
     *
     * <code>.Hmi hmi = 2;</code>
     */
    boolean hasHmi();
    /**
     * <pre>
     * HMI消息
     * </pre>
     *
     * <code>.Hmi hmi = 2;</code>
     */
    HmiOuterClass.Hmi getHmi();
    /**
     * <pre>
     * HMI消息
     * </pre>
     *
     * <code>.Hmi hmi = 2;</code>
     */
    HmiOuterClass.HmiOrBuilder getHmiOrBuilder();
  }
  /**
   * <pre>
   * 最外层消息
   * </pre>
   *
   * Protobuf type {@code Icdc2Hmi}
   */
  public  static final class Icdc2Hmi extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Icdc2Hmi)
      Icdc2HmiOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Icdc2Hmi.newBuilder() to construct.
    private Icdc2Hmi(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Icdc2Hmi() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Icdc2Hmi(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              HeadOuterClass.Head.Builder subBuilder = null;
              if (head_ != null) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(HeadOuterClass.Head.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              HmiOuterClass.Hmi.Builder subBuilder = null;
              if (hmi_ != null) {
                subBuilder = hmi_.toBuilder();
              }
              hmi_ = input.readMessage(HmiOuterClass.Hmi.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hmi_);
                hmi_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Icdc2HmiOuterClass.internal_static_Icdc2Hmi_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Icdc2HmiOuterClass.internal_static_Icdc2Hmi_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Icdc2HmiOuterClass.Icdc2Hmi.class, Icdc2HmiOuterClass.Icdc2Hmi.Builder.class);
    }

    public static final int HEAD_FIELD_NUMBER = 1;
    private HeadOuterClass.Head head_;
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Head head = 1;</code>
     */
    public boolean hasHead() {
      return head_ != null;
    }
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Head head = 1;</code>
     */
    public HeadOuterClass.Head getHead() {
      return head_ == null ? HeadOuterClass.Head.getDefaultInstance() : head_;
    }
    /**
     * <pre>
     * 消息头
     * </pre>
     *
     * <code>.Head head = 1;</code>
     */
    public HeadOuterClass.HeadOrBuilder getHeadOrBuilder() {
      return getHead();
    }

    public static final int HMI_FIELD_NUMBER = 2;
    private HmiOuterClass.Hmi hmi_;
    /**
     * <pre>
     * HMI消息
     * </pre>
     *
     * <code>.Hmi hmi = 2;</code>
     */
    public boolean hasHmi() {
      return hmi_ != null;
    }
    /**
     * <pre>
     * HMI消息
     * </pre>
     *
     * <code>.Hmi hmi = 2;</code>
     */
    public HmiOuterClass.Hmi getHmi() {
      return hmi_ == null ? HmiOuterClass.Hmi.getDefaultInstance() : hmi_;
    }
    /**
     * <pre>
     * HMI消息
     * </pre>
     *
     * <code>.Hmi hmi = 2;</code>
     */
    public HmiOuterClass.HmiOrBuilder getHmiOrBuilder() {
      return getHmi();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (head_ != null) {
        output.writeMessage(1, getHead());
      }
      if (hmi_ != null) {
        output.writeMessage(2, getHmi());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (head_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHead());
      }
      if (hmi_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHmi());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Icdc2HmiOuterClass.Icdc2Hmi)) {
        return super.equals(obj);
      }
      Icdc2HmiOuterClass.Icdc2Hmi other = (Icdc2HmiOuterClass.Icdc2Hmi) obj;

      boolean result = true;
      result = result && (hasHead() == other.hasHead());
      if (hasHead()) {
        result = result && getHead()
            .equals(other.getHead());
      }
      result = result && (hasHmi() == other.hasHmi());
      if (hasHmi()) {
        result = result && getHmi()
            .equals(other.getHmi());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHead()) {
        hash = (37 * hash) + HEAD_FIELD_NUMBER;
        hash = (53 * hash) + getHead().hashCode();
      }
      if (hasHmi()) {
        hash = (37 * hash) + HMI_FIELD_NUMBER;
        hash = (53 * hash) + getHmi().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Icdc2HmiOuterClass.Icdc2Hmi parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Icdc2HmiOuterClass.Icdc2Hmi prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 最外层消息
     * </pre>
     *
     * Protobuf type {@code Icdc2Hmi}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Icdc2Hmi)
        Icdc2HmiOuterClass.Icdc2HmiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Icdc2HmiOuterClass.internal_static_Icdc2Hmi_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Icdc2HmiOuterClass.internal_static_Icdc2Hmi_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Icdc2HmiOuterClass.Icdc2Hmi.class, Icdc2HmiOuterClass.Icdc2Hmi.Builder.class);
      }

      // Construct using Icdc2HmiOuterClass.Icdc2Hmi.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = null;
        } else {
          head_ = null;
          headBuilder_ = null;
        }
        if (hmiBuilder_ == null) {
          hmi_ = null;
        } else {
          hmi_ = null;
          hmiBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Icdc2HmiOuterClass.internal_static_Icdc2Hmi_descriptor;
      }

      public Icdc2HmiOuterClass.Icdc2Hmi getDefaultInstanceForType() {
        return Icdc2HmiOuterClass.Icdc2Hmi.getDefaultInstance();
      }

      public Icdc2HmiOuterClass.Icdc2Hmi build() {
        Icdc2HmiOuterClass.Icdc2Hmi result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Icdc2HmiOuterClass.Icdc2Hmi buildPartial() {
        Icdc2HmiOuterClass.Icdc2Hmi result = new Icdc2HmiOuterClass.Icdc2Hmi(this);
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (hmiBuilder_ == null) {
          result.hmi_ = hmi_;
        } else {
          result.hmi_ = hmiBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Icdc2HmiOuterClass.Icdc2Hmi) {
          return mergeFrom((Icdc2HmiOuterClass.Icdc2Hmi)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Icdc2HmiOuterClass.Icdc2Hmi other) {
        if (other == Icdc2HmiOuterClass.Icdc2Hmi.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.hasHmi()) {
          mergeHmi(other.getHmi());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Icdc2HmiOuterClass.Icdc2Hmi parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Icdc2HmiOuterClass.Icdc2Hmi) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private HeadOuterClass.Head head_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          HeadOuterClass.Head, HeadOuterClass.Head.Builder, HeadOuterClass.HeadOrBuilder> headBuilder_;
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public boolean hasHead() {
        return headBuilder_ != null || head_ != null;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public HeadOuterClass.Head getHead() {
        if (headBuilder_ == null) {
          return head_ == null ? HeadOuterClass.Head.getDefaultInstance() : head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public Builder setHead(HeadOuterClass.Head value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public Builder setHead(
          HeadOuterClass.Head.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public Builder mergeHead(HeadOuterClass.Head value) {
        if (headBuilder_ == null) {
          if (head_ != null) {
            head_ =
              HeadOuterClass.Head.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = null;
          onChanged();
        } else {
          head_ = null;
          headBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public HeadOuterClass.Head.Builder getHeadBuilder() {

        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      public HeadOuterClass.HeadOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_ == null ?
              HeadOuterClass.Head.getDefaultInstance() : head_;
        }
      }
      /**
       * <pre>
       * 消息头
       * </pre>
       *
       * <code>.Head head = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          HeadOuterClass.Head, HeadOuterClass.Head.Builder, HeadOuterClass.HeadOrBuilder>
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              HeadOuterClass.Head, HeadOuterClass.Head.Builder, HeadOuterClass.HeadOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      private HmiOuterClass.Hmi hmi_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          HmiOuterClass.Hmi, HmiOuterClass.Hmi.Builder, HmiOuterClass.HmiOrBuilder> hmiBuilder_;
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public boolean hasHmi() {
        return hmiBuilder_ != null || hmi_ != null;
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public HmiOuterClass.Hmi getHmi() {
        if (hmiBuilder_ == null) {
          return hmi_ == null ? HmiOuterClass.Hmi.getDefaultInstance() : hmi_;
        } else {
          return hmiBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public Builder setHmi(HmiOuterClass.Hmi value) {
        if (hmiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hmi_ = value;
          onChanged();
        } else {
          hmiBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public Builder setHmi(
          HmiOuterClass.Hmi.Builder builderForValue) {
        if (hmiBuilder_ == null) {
          hmi_ = builderForValue.build();
          onChanged();
        } else {
          hmiBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public Builder mergeHmi(HmiOuterClass.Hmi value) {
        if (hmiBuilder_ == null) {
          if (hmi_ != null) {
            hmi_ =
              HmiOuterClass.Hmi.newBuilder(hmi_).mergeFrom(value).buildPartial();
          } else {
            hmi_ = value;
          }
          onChanged();
        } else {
          hmiBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public Builder clearHmi() {
        if (hmiBuilder_ == null) {
          hmi_ = null;
          onChanged();
        } else {
          hmi_ = null;
          hmiBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public HmiOuterClass.Hmi.Builder getHmiBuilder() {

        onChanged();
        return getHmiFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      public HmiOuterClass.HmiOrBuilder getHmiOrBuilder() {
        if (hmiBuilder_ != null) {
          return hmiBuilder_.getMessageOrBuilder();
        } else {
          return hmi_ == null ?
              HmiOuterClass.Hmi.getDefaultInstance() : hmi_;
        }
      }
      /**
       * <pre>
       * HMI消息
       * </pre>
       *
       * <code>.Hmi hmi = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          HmiOuterClass.Hmi, HmiOuterClass.Hmi.Builder, HmiOuterClass.HmiOrBuilder>
          getHmiFieldBuilder() {
        if (hmiBuilder_ == null) {
          hmiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              HmiOuterClass.Hmi, HmiOuterClass.Hmi.Builder, HmiOuterClass.HmiOrBuilder>(
                  getHmi(),
                  getParentForChildren(),
                  isClean());
          hmi_ = null;
        }
        return hmiBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Icdc2Hmi)
    }

    // @@protoc_insertion_point(class_scope:Icdc2Hmi)
    private static final Icdc2HmiOuterClass.Icdc2Hmi DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Icdc2HmiOuterClass.Icdc2Hmi();
    }

    public static Icdc2HmiOuterClass.Icdc2Hmi getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Icdc2Hmi>
        PARSER = new com.google.protobuf.AbstractParser<Icdc2Hmi>() {
      public Icdc2Hmi parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Icdc2Hmi(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Icdc2Hmi> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Icdc2Hmi> getParserForType() {
      return PARSER;
    }

    public Icdc2HmiOuterClass.Icdc2Hmi getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Icdc2Hmi_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Icdc2Hmi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Icdc2Hmi.proto\032\tHmi.proto\032\nHead.proto\"" +
      "2\n\010Icdc2Hmi\022\023\n\004head\030\001 \001(\0132\005.Head\022\021\n\003hmi\030" +
      "\002 \001(\0132\004.Hmib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          HmiOuterClass.getDescriptor(),
          HeadOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Icdc2Hmi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Icdc2Hmi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Icdc2Hmi_descriptor,
        new String[] { "Head", "Hmi", });
    HmiOuterClass.getDescriptor();
    HeadOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
