package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Metadata.proto

public final class MetadataOuterClass {
  private MetadataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 交通参与者唯一id,使用utf-8
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    String getUUID();
    /**
     * <pre>
     * 交通参与者唯一id,使用utf-8
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    com.google.protobuf.ByteString
        getUUIDBytes();

    /**
     * <pre>
     * 交通参与者类型
     * </pre>
     *
     * <code>.Metadata.Type type = 2;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * 交通参与者类型
     * </pre>
     *
     * <code>.Metadata.Type type = 2;</code>
     */
    MetadataOuterClass.Metadata.Type getType();

    /**
     * <pre>
     * 交通参与者的位置信息
     * </pre>
     *
     * <code>.Position position = 3;</code>
     */
    boolean hasPosition();
    /**
     * <pre>
     * 交通参与者的位置信息
     * </pre>
     *
     * <code>.Position position = 3;</code>
     */
    PositionOuterClass.Position getPosition();
    /**
     * <pre>
     * 交通参与者的位置信息
     * </pre>
     *
     * <code>.Position position = 3;</code>
     */
    PositionOuterClass.PositionOrBuilder getPositionOrBuilder();

    /**
     * <pre>
     * 交通参与者相对于主车的方位
     * </pre>
     *
     * <code>.Metadata.Direction direction = 4;</code>
     */
    int getDirectionValue();
    /**
     * <pre>
     * 交通参与者相对于主车的方位
     * </pre>
     *
     * <code>.Metadata.Direction direction = 4;</code>
     */
    MetadataOuterClass.Metadata.Direction getDirection();

    /**
     * <pre>
     * 交通参与者的速度
     * </pre>
     *
     * <code>float speed = 5;</code>
     */
    float getSpeed();

    /**
     * <pre>
     * 交通参与者的航向角,以正北为0度,顺时针 0-360
     * </pre>
     *
     * <code>float heading = 6;</code>
     */
    float getHeading();

    /**
     * <pre>
     * 交通参与者长宽高,单位:米
     * </pre>
     *
     * <code>float length = 7;</code>
     */
    float getLength();

    /**
     * <code>float width = 8;</code>
     */
    float getWidth();

    /**
     * <code>float height = 9;</code>
     */
    float getHeight();

    /**
     * <pre>
     * 交通参与者的相对主车距离,单位:米
     * </pre>
     *
     * <code>float relativeDistance = 10;</code>
     */
    float getRelativeDistance();

    /**
     * <code>float relativeDistanceX = 11;</code>
     */
    float getRelativeDistanceX();

    /**
     * <code>float relativeDistanceY = 12;</code>
     */
    float getRelativeDistanceY();
  }
  /**
   * <pre>
   * 场景元数据,当前数据规划中,还未开发
   * </pre>
   *
   * Protobuf type {@code Metadata}
   */
  public  static final class Metadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Metadata)
      MetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
      uUID_ = "";
      type_ = 0;
      direction_ = 0;
      speed_ = 0F;
      heading_ = 0F;
      length_ = 0F;
      width_ = 0F;
      height_ = 0F;
      relativeDistance_ = 0F;
      relativeDistanceX_ = 0F;
      relativeDistanceY_ = 0F;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Metadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              uUID_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              PositionOuterClass.Position.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(PositionOuterClass.Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              direction_ = rawValue;
              break;
            }
            case 45: {

              speed_ = input.readFloat();
              break;
            }
            case 53: {

              heading_ = input.readFloat();
              break;
            }
            case 61: {

              length_ = input.readFloat();
              break;
            }
            case 69: {

              width_ = input.readFloat();
              break;
            }
            case 77: {

              height_ = input.readFloat();
              break;
            }
            case 85: {

              relativeDistance_ = input.readFloat();
              break;
            }
            case 93: {

              relativeDistanceX_ = input.readFloat();
              break;
            }
            case 101: {

              relativeDistanceY_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MetadataOuterClass.internal_static_Metadata_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MetadataOuterClass.internal_static_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MetadataOuterClass.Metadata.class, MetadataOuterClass.Metadata.Builder.class);
    }

    /**
     * Protobuf enum {@code Metadata.Direction}
     */
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 未知
       * </pre>
       *
       * <code>DIRECTION_UNKNOWN = 0;</code>
       */
      DIRECTION_UNKNOWN(0),
      /**
       * <pre>
       * 正前
       * </pre>
       *
       * <code>FRONT = 1;</code>
       */
      FRONT(1),
      /**
       * <pre>
       * 正后
       * </pre>
       *
       * <code>REAR = 2;</code>
       */
      REAR(2),
      /**
       * <pre>
       * 左前
       * </pre>
       *
       * <code>LEFT_FRONT = 3;</code>
       */
      LEFT_FRONT(3),
      /**
       * <pre>
       * 左后
       * </pre>
       *
       * <code>LEFT_REAR = 4;</code>
       */
      LEFT_REAR(4),
      /**
       * <pre>
       * 右前
       * </pre>
       *
       * <code>RIGHT_FRONT = 5;</code>
       */
      RIGHT_FRONT(5),
      /**
       * <pre>
       * 右后
       * </pre>
       *
       * <code>RIGHT_REAR = 6;</code>
       */
      RIGHT_REAR(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 未知
       * </pre>
       *
       * <code>DIRECTION_UNKNOWN = 0;</code>
       */
      public static final int DIRECTION_UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * 正前
       * </pre>
       *
       * <code>FRONT = 1;</code>
       */
      public static final int FRONT_VALUE = 1;
      /**
       * <pre>
       * 正后
       * </pre>
       *
       * <code>REAR = 2;</code>
       */
      public static final int REAR_VALUE = 2;
      /**
       * <pre>
       * 左前
       * </pre>
       *
       * <code>LEFT_FRONT = 3;</code>
       */
      public static final int LEFT_FRONT_VALUE = 3;
      /**
       * <pre>
       * 左后
       * </pre>
       *
       * <code>LEFT_REAR = 4;</code>
       */
      public static final int LEFT_REAR_VALUE = 4;
      /**
       * <pre>
       * 右前
       * </pre>
       *
       * <code>RIGHT_FRONT = 5;</code>
       */
      public static final int RIGHT_FRONT_VALUE = 5;
      /**
       * <pre>
       * 右后
       * </pre>
       *
       * <code>RIGHT_REAR = 6;</code>
       */
      public static final int RIGHT_REAR_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Direction valueOf(int value) {
        return forNumber(value);
      }

      public static Direction forNumber(int value) {
        switch (value) {
          case 0: return DIRECTION_UNKNOWN;
          case 1: return FRONT;
          case 2: return REAR;
          case 3: return LEFT_FRONT;
          case 4: return LEFT_REAR;
          case 5: return RIGHT_FRONT;
          case 6: return RIGHT_REAR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Direction> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MetadataOuterClass.Metadata.getDescriptor().getEnumTypes().get(0);
      }

      private static final Direction[] VALUES = values();

      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Direction(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Metadata.Direction)
    }

    /**
     * Protobuf enum {@code Metadata.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 未知
       * </pre>
       *
       * <code>TYPE_UNKNOWN = 0;</code>
       */
      TYPE_UNKNOWN(0),
      /**
       * <pre>
       * 机动车
       * </pre>
       *
       * <code>Vehicle = 1;</code>
       */
      Vehicle(1),
      /**
       * <pre>
       * 非机动车
       * </pre>
       *
       * <code>Non_Motor = 2;</code>
       */
      Non_Motor(2),
      /**
       * <pre>
       * 人
       * </pre>
       *
       * <code>MAN = 3;</code>
       */
      MAN(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 未知
       * </pre>
       *
       * <code>TYPE_UNKNOWN = 0;</code>
       */
      public static final int TYPE_UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * 机动车
       * </pre>
       *
       * <code>Vehicle = 1;</code>
       */
      public static final int Vehicle_VALUE = 1;
      /**
       * <pre>
       * 非机动车
       * </pre>
       *
       * <code>Non_Motor = 2;</code>
       */
      public static final int Non_Motor_VALUE = 2;
      /**
       * <pre>
       * 人
       * </pre>
       *
       * <code>MAN = 3;</code>
       */
      public static final int MAN_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return TYPE_UNKNOWN;
          case 1: return Vehicle;
          case 2: return Non_Motor;
          case 3: return MAN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MetadataOuterClass.Metadata.getDescriptor().getEnumTypes().get(1);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Metadata.Type)
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile Object uUID_;
    /**
     * <pre>
     * 交通参与者唯一id,使用utf-8
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    public String getUUID() {
      Object ref = uUID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uUID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 交通参与者唯一id,使用utf-8
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      Object ref = uUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     * 交通参与者类型
     * </pre>
     *
     * <code>.Metadata.Type type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 交通参与者类型
     * </pre>
     *
     * <code>.Metadata.Type type = 2;</code>
     */
    public MetadataOuterClass.Metadata.Type getType() {
      MetadataOuterClass.Metadata.Type result = MetadataOuterClass.Metadata.Type.valueOf(type_);
      return result == null ? MetadataOuterClass.Metadata.Type.UNRECOGNIZED : result;
    }

    public static final int POSITION_FIELD_NUMBER = 3;
    private PositionOuterClass.Position position_;
    /**
     * <pre>
     * 交通参与者的位置信息
     * </pre>
     *
     * <code>.Position position = 3;</code>
     */
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <pre>
     * 交通参与者的位置信息
     * </pre>
     *
     * <code>.Position position = 3;</code>
     */
    public PositionOuterClass.Position getPosition() {
      return position_ == null ? PositionOuterClass.Position.getDefaultInstance() : position_;
    }
    /**
     * <pre>
     * 交通参与者的位置信息
     * </pre>
     *
     * <code>.Position position = 3;</code>
     */
    public PositionOuterClass.PositionOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int DIRECTION_FIELD_NUMBER = 4;
    private int direction_;
    /**
     * <pre>
     * 交通参与者相对于主车的方位
     * </pre>
     *
     * <code>.Metadata.Direction direction = 4;</code>
     */
    public int getDirectionValue() {
      return direction_;
    }
    /**
     * <pre>
     * 交通参与者相对于主车的方位
     * </pre>
     *
     * <code>.Metadata.Direction direction = 4;</code>
     */
    public MetadataOuterClass.Metadata.Direction getDirection() {
      MetadataOuterClass.Metadata.Direction result = MetadataOuterClass.Metadata.Direction.valueOf(direction_);
      return result == null ? MetadataOuterClass.Metadata.Direction.UNRECOGNIZED : result;
    }

    public static final int SPEED_FIELD_NUMBER = 5;
    private float speed_;
    /**
     * <pre>
     * 交通参与者的速度
     * </pre>
     *
     * <code>float speed = 5;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    public static final int HEADING_FIELD_NUMBER = 6;
    private float heading_;
    /**
     * <pre>
     * 交通参与者的航向角,以正北为0度,顺时针 0-360
     * </pre>
     *
     * <code>float heading = 6;</code>
     */
    public float getHeading() {
      return heading_;
    }

    public static final int LENGTH_FIELD_NUMBER = 7;
    private float length_;
    /**
     * <pre>
     * 交通参与者长宽高,单位:米
     * </pre>
     *
     * <code>float length = 7;</code>
     */
    public float getLength() {
      return length_;
    }

    public static final int WIDTH_FIELD_NUMBER = 8;
    private float width_;
    /**
     * <code>float width = 8;</code>
     */
    public float getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 9;
    private float height_;
    /**
     * <code>float height = 9;</code>
     */
    public float getHeight() {
      return height_;
    }

    public static final int RELATIVEDISTANCE_FIELD_NUMBER = 10;
    private float relativeDistance_;
    /**
     * <pre>
     * 交通参与者的相对主车距离,单位:米
     * </pre>
     *
     * <code>float relativeDistance = 10;</code>
     */
    public float getRelativeDistance() {
      return relativeDistance_;
    }

    public static final int RELATIVEDISTANCEX_FIELD_NUMBER = 11;
    private float relativeDistanceX_;
    /**
     * <code>float relativeDistanceX = 11;</code>
     */
    public float getRelativeDistanceX() {
      return relativeDistanceX_;
    }

    public static final int RELATIVEDISTANCEY_FIELD_NUMBER = 12;
    private float relativeDistanceY_;
    /**
     * <code>float relativeDistanceY = 12;</code>
     */
    public float getRelativeDistanceY() {
      return relativeDistanceY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uUID_);
      }
      if (type_ != MetadataOuterClass.Metadata.Type.TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (position_ != null) {
        output.writeMessage(3, getPosition());
      }
      if (direction_ != MetadataOuterClass.Metadata.Direction.DIRECTION_UNKNOWN.getNumber()) {
        output.writeEnum(4, direction_);
      }
      if (speed_ != 0F) {
        output.writeFloat(5, speed_);
      }
      if (heading_ != 0F) {
        output.writeFloat(6, heading_);
      }
      if (length_ != 0F) {
        output.writeFloat(7, length_);
      }
      if (width_ != 0F) {
        output.writeFloat(8, width_);
      }
      if (height_ != 0F) {
        output.writeFloat(9, height_);
      }
      if (relativeDistance_ != 0F) {
        output.writeFloat(10, relativeDistance_);
      }
      if (relativeDistanceX_ != 0F) {
        output.writeFloat(11, relativeDistanceX_);
      }
      if (relativeDistanceY_ != 0F) {
        output.writeFloat(12, relativeDistanceY_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uUID_);
      }
      if (type_ != MetadataOuterClass.Metadata.Type.TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPosition());
      }
      if (direction_ != MetadataOuterClass.Metadata.Direction.DIRECTION_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, direction_);
      }
      if (speed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, speed_);
      }
      if (heading_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, heading_);
      }
      if (length_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, length_);
      }
      if (width_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, width_);
      }
      if (height_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, height_);
      }
      if (relativeDistance_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, relativeDistance_);
      }
      if (relativeDistanceX_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, relativeDistanceX_);
      }
      if (relativeDistanceY_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, relativeDistanceY_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MetadataOuterClass.Metadata)) {
        return super.equals(obj);
      }
      MetadataOuterClass.Metadata other = (MetadataOuterClass.Metadata) obj;

      boolean result = true;
      result = result && getUUID()
          .equals(other.getUUID());
      result = result && type_ == other.type_;
      result = result && (hasPosition() == other.hasPosition());
      if (hasPosition()) {
        result = result && getPosition()
            .equals(other.getPosition());
      }
      result = result && direction_ == other.direction_;
      result = result && (
          Float.floatToIntBits(getSpeed())
          == Float.floatToIntBits(
              other.getSpeed()));
      result = result && (
          Float.floatToIntBits(getHeading())
          == Float.floatToIntBits(
              other.getHeading()));
      result = result && (
          Float.floatToIntBits(getLength())
          == Float.floatToIntBits(
              other.getLength()));
      result = result && (
          Float.floatToIntBits(getWidth())
          == Float.floatToIntBits(
              other.getWidth()));
      result = result && (
          Float.floatToIntBits(getHeight())
          == Float.floatToIntBits(
              other.getHeight()));
      result = result && (
          Float.floatToIntBits(getRelativeDistance())
          == Float.floatToIntBits(
              other.getRelativeDistance()));
      result = result && (
          Float.floatToIntBits(getRelativeDistanceX())
          == Float.floatToIntBits(
              other.getRelativeDistanceX()));
      result = result && (
          Float.floatToIntBits(getRelativeDistanceY())
          == Float.floatToIntBits(
              other.getRelativeDistanceY()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUUID().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + direction_;
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + HEADING_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getHeading());
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getLength());
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getWidth());
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getHeight());
      hash = (37 * hash) + RELATIVEDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRelativeDistance());
      hash = (37 * hash) + RELATIVEDISTANCEX_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRelativeDistanceX());
      hash = (37 * hash) + RELATIVEDISTANCEY_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRelativeDistanceY());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MetadataOuterClass.Metadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MetadataOuterClass.Metadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MetadataOuterClass.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MetadataOuterClass.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MetadataOuterClass.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MetadataOuterClass.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MetadataOuterClass.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MetadataOuterClass.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MetadataOuterClass.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MetadataOuterClass.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MetadataOuterClass.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MetadataOuterClass.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MetadataOuterClass.Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 场景元数据,当前数据规划中,还未开发
     * </pre>
     *
     * Protobuf type {@code Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Metadata)
        MetadataOuterClass.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MetadataOuterClass.internal_static_Metadata_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MetadataOuterClass.internal_static_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MetadataOuterClass.Metadata.class, MetadataOuterClass.Metadata.Builder.class);
      }

      // Construct using MetadataOuterClass.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uUID_ = "";

        type_ = 0;

        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        direction_ = 0;

        speed_ = 0F;

        heading_ = 0F;

        length_ = 0F;

        width_ = 0F;

        height_ = 0F;

        relativeDistance_ = 0F;

        relativeDistanceX_ = 0F;

        relativeDistanceY_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MetadataOuterClass.internal_static_Metadata_descriptor;
      }

      public MetadataOuterClass.Metadata getDefaultInstanceForType() {
        return MetadataOuterClass.Metadata.getDefaultInstance();
      }

      public MetadataOuterClass.Metadata build() {
        MetadataOuterClass.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MetadataOuterClass.Metadata buildPartial() {
        MetadataOuterClass.Metadata result = new MetadataOuterClass.Metadata(this);
        result.uUID_ = uUID_;
        result.type_ = type_;
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.direction_ = direction_;
        result.speed_ = speed_;
        result.heading_ = heading_;
        result.length_ = length_;
        result.width_ = width_;
        result.height_ = height_;
        result.relativeDistance_ = relativeDistance_;
        result.relativeDistanceX_ = relativeDistanceX_;
        result.relativeDistanceY_ = relativeDistanceY_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MetadataOuterClass.Metadata) {
          return mergeFrom((MetadataOuterClass.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MetadataOuterClass.Metadata other) {
        if (other == MetadataOuterClass.Metadata.getDefaultInstance()) return this;
        if (!other.getUUID().isEmpty()) {
          uUID_ = other.uUID_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.direction_ != 0) {
          setDirectionValue(other.getDirectionValue());
        }
        if (other.getSpeed() != 0F) {
          setSpeed(other.getSpeed());
        }
        if (other.getHeading() != 0F) {
          setHeading(other.getHeading());
        }
        if (other.getLength() != 0F) {
          setLength(other.getLength());
        }
        if (other.getWidth() != 0F) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (other.getRelativeDistance() != 0F) {
          setRelativeDistance(other.getRelativeDistance());
        }
        if (other.getRelativeDistanceX() != 0F) {
          setRelativeDistanceX(other.getRelativeDistanceX());
        }
        if (other.getRelativeDistanceY() != 0F) {
          setRelativeDistanceY(other.getRelativeDistanceY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MetadataOuterClass.Metadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MetadataOuterClass.Metadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object uUID_ = "";
      /**
       * <pre>
       * 交通参与者唯一id,使用utf-8
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public String getUUID() {
        Object ref = uUID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uUID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 交通参与者唯一id,使用utf-8
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUUIDBytes() {
        Object ref = uUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 交通参与者唯一id,使用utf-8
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder setUUID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        uUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者唯一id,使用utf-8
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder clearUUID() {

        uUID_ = getDefaultInstance().getUUID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者唯一id,使用utf-8
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder setUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        uUID_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 交通参与者类型
       * </pre>
       *
       * <code>.Metadata.Type type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 交通参与者类型
       * </pre>
       *
       * <code>.Metadata.Type type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者类型
       * </pre>
       *
       * <code>.Metadata.Type type = 2;</code>
       */
      public MetadataOuterClass.Metadata.Type getType() {
        MetadataOuterClass.Metadata.Type result = MetadataOuterClass.Metadata.Type.valueOf(type_);
        return result == null ? MetadataOuterClass.Metadata.Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 交通参与者类型
       * </pre>
       *
       * <code>.Metadata.Type type = 2;</code>
       */
      public Builder setType(MetadataOuterClass.Metadata.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }

        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者类型
       * </pre>
       *
       * <code>.Metadata.Type type = 2;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private PositionOuterClass.Position position_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          PositionOuterClass.Position, PositionOuterClass.Position.Builder, PositionOuterClass.PositionOrBuilder> positionBuilder_;
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public PositionOuterClass.Position getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? PositionOuterClass.Position.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public Builder setPosition(PositionOuterClass.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public Builder setPosition(
          PositionOuterClass.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public Builder mergePosition(PositionOuterClass.Position value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              PositionOuterClass.Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public PositionOuterClass.Position.Builder getPositionBuilder() {

        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      public PositionOuterClass.PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              PositionOuterClass.Position.getDefaultInstance() : position_;
        }
      }
      /**
       * <pre>
       * 交通参与者的位置信息
       * </pre>
       *
       * <code>.Position position = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PositionOuterClass.Position, PositionOuterClass.Position.Builder, PositionOuterClass.PositionOrBuilder>
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PositionOuterClass.Position, PositionOuterClass.Position.Builder, PositionOuterClass.PositionOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private int direction_ = 0;
      /**
       * <pre>
       * 交通参与者相对于主车的方位
       * </pre>
       *
       * <code>.Metadata.Direction direction = 4;</code>
       */
      public int getDirectionValue() {
        return direction_;
      }
      /**
       * <pre>
       * 交通参与者相对于主车的方位
       * </pre>
       *
       * <code>.Metadata.Direction direction = 4;</code>
       */
      public Builder setDirectionValue(int value) {
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者相对于主车的方位
       * </pre>
       *
       * <code>.Metadata.Direction direction = 4;</code>
       */
      public MetadataOuterClass.Metadata.Direction getDirection() {
        MetadataOuterClass.Metadata.Direction result = MetadataOuterClass.Metadata.Direction.valueOf(direction_);
        return result == null ? MetadataOuterClass.Metadata.Direction.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 交通参与者相对于主车的方位
       * </pre>
       *
       * <code>.Metadata.Direction direction = 4;</code>
       */
      public Builder setDirection(MetadataOuterClass.Metadata.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }

        direction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者相对于主车的方位
       * </pre>
       *
       * <code>.Metadata.Direction direction = 4;</code>
       */
      public Builder clearDirection() {

        direction_ = 0;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <pre>
       * 交通参与者的速度
       * </pre>
       *
       * <code>float speed = 5;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <pre>
       * 交通参与者的速度
       * </pre>
       *
       * <code>float speed = 5;</code>
       */
      public Builder setSpeed(float value) {

        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者的速度
       * </pre>
       *
       * <code>float speed = 5;</code>
       */
      public Builder clearSpeed() {

        speed_ = 0F;
        onChanged();
        return this;
      }

      private float heading_ ;
      /**
       * <pre>
       * 交通参与者的航向角,以正北为0度,顺时针 0-360
       * </pre>
       *
       * <code>float heading = 6;</code>
       */
      public float getHeading() {
        return heading_;
      }
      /**
       * <pre>
       * 交通参与者的航向角,以正北为0度,顺时针 0-360
       * </pre>
       *
       * <code>float heading = 6;</code>
       */
      public Builder setHeading(float value) {

        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者的航向角,以正北为0度,顺时针 0-360
       * </pre>
       *
       * <code>float heading = 6;</code>
       */
      public Builder clearHeading() {

        heading_ = 0F;
        onChanged();
        return this;
      }

      private float length_ ;
      /**
       * <pre>
       * 交通参与者长宽高,单位:米
       * </pre>
       *
       * <code>float length = 7;</code>
       */
      public float getLength() {
        return length_;
      }
      /**
       * <pre>
       * 交通参与者长宽高,单位:米
       * </pre>
       *
       * <code>float length = 7;</code>
       */
      public Builder setLength(float value) {

        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者长宽高,单位:米
       * </pre>
       *
       * <code>float length = 7;</code>
       */
      public Builder clearLength() {

        length_ = 0F;
        onChanged();
        return this;
      }

      private float width_ ;
      /**
       * <code>float width = 8;</code>
       */
      public float getWidth() {
        return width_;
      }
      /**
       * <code>float width = 8;</code>
       */
      public Builder setWidth(float value) {

        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float width = 8;</code>
       */
      public Builder clearWidth() {

        width_ = 0F;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <code>float height = 9;</code>
       */
      public float getHeight() {
        return height_;
      }
      /**
       * <code>float height = 9;</code>
       */
      public Builder setHeight(float value) {

        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float height = 9;</code>
       */
      public Builder clearHeight() {

        height_ = 0F;
        onChanged();
        return this;
      }

      private float relativeDistance_ ;
      /**
       * <pre>
       * 交通参与者的相对主车距离,单位:米
       * </pre>
       *
       * <code>float relativeDistance = 10;</code>
       */
      public float getRelativeDistance() {
        return relativeDistance_;
      }
      /**
       * <pre>
       * 交通参与者的相对主车距离,单位:米
       * </pre>
       *
       * <code>float relativeDistance = 10;</code>
       */
      public Builder setRelativeDistance(float value) {

        relativeDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交通参与者的相对主车距离,单位:米
       * </pre>
       *
       * <code>float relativeDistance = 10;</code>
       */
      public Builder clearRelativeDistance() {

        relativeDistance_ = 0F;
        onChanged();
        return this;
      }

      private float relativeDistanceX_ ;
      /**
       * <code>float relativeDistanceX = 11;</code>
       */
      public float getRelativeDistanceX() {
        return relativeDistanceX_;
      }
      /**
       * <code>float relativeDistanceX = 11;</code>
       */
      public Builder setRelativeDistanceX(float value) {

        relativeDistanceX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float relativeDistanceX = 11;</code>
       */
      public Builder clearRelativeDistanceX() {

        relativeDistanceX_ = 0F;
        onChanged();
        return this;
      }

      private float relativeDistanceY_ ;
      /**
       * <code>float relativeDistanceY = 12;</code>
       */
      public float getRelativeDistanceY() {
        return relativeDistanceY_;
      }
      /**
       * <code>float relativeDistanceY = 12;</code>
       */
      public Builder setRelativeDistanceY(float value) {

        relativeDistanceY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float relativeDistanceY = 12;</code>
       */
      public Builder clearRelativeDistanceY() {

        relativeDistanceY_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Metadata)
    }

    // @@protoc_insertion_point(class_scope:Metadata)
    private static final MetadataOuterClass.Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MetadataOuterClass.Metadata();
    }

    public static MetadataOuterClass.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Metadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    public MetadataOuterClass.Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetadataListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MetadataList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    java.util.List<Metadata>
        getMetadataList();
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    MetadataOuterClass.Metadata getMetadata(int index);
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    int getMetadataCount();
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    java.util.List<? extends MetadataOrBuilder>
        getMetadataOrBuilderList();
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    MetadataOuterClass.MetadataOrBuilder getMetadataOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code MetadataList}
   */
  public  static final class MetadataList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MetadataList)
      MetadataListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MetadataList.newBuilder() to construct.
    private MetadataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetadataList() {
      metadata_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MetadataList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                metadata_ = new java.util.ArrayList<Metadata>();
                mutable_bitField0_ |= 0x00000001;
              }
              metadata_.add(
                  input.readMessage(MetadataOuterClass.Metadata.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          metadata_ = java.util.Collections.unmodifiableList(metadata_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MetadataOuterClass.internal_static_MetadataList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MetadataOuterClass.internal_static_MetadataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MetadataOuterClass.MetadataList.class, MetadataOuterClass.MetadataList.Builder.class);
    }

    public static final int METADATA_FIELD_NUMBER = 1;
    private java.util.List<Metadata> metadata_;
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    public java.util.List<Metadata> getMetadataList() {
      return metadata_;
    }
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    public java.util.List<? extends MetadataOrBuilder>
        getMetadataOrBuilderList() {
      return metadata_;
    }
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    public int getMetadataCount() {
      return metadata_.size();
    }
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    public MetadataOuterClass.Metadata getMetadata(int index) {
      return metadata_.get(index);
    }
    /**
     * <code>repeated .Metadata metadata = 1;</code>
     */
    public MetadataOuterClass.MetadataOrBuilder getMetadataOrBuilder(
        int index) {
      return metadata_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < metadata_.size(); i++) {
        output.writeMessage(1, metadata_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < metadata_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, metadata_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MetadataOuterClass.MetadataList)) {
        return super.equals(obj);
      }
      MetadataOuterClass.MetadataList other = (MetadataOuterClass.MetadataList) obj;

      boolean result = true;
      result = result && getMetadataList()
          .equals(other.getMetadataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMetadataCount() > 0) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MetadataOuterClass.MetadataList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MetadataOuterClass.MetadataList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MetadataOuterClass.MetadataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MetadataOuterClass.MetadataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MetadataOuterClass.MetadataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MetadataOuterClass.MetadataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MetadataOuterClass.MetadataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MetadataOuterClass.MetadataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MetadataOuterClass.MetadataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MetadataOuterClass.MetadataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MetadataOuterClass.MetadataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MetadataOuterClass.MetadataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MetadataOuterClass.MetadataList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MetadataList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MetadataList)
        MetadataOuterClass.MetadataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MetadataOuterClass.internal_static_MetadataList_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MetadataOuterClass.internal_static_MetadataList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MetadataOuterClass.MetadataList.class, MetadataOuterClass.MetadataList.Builder.class);
      }

      // Construct using MetadataOuterClass.MetadataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMetadataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (metadataBuilder_ == null) {
          metadata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          metadataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MetadataOuterClass.internal_static_MetadataList_descriptor;
      }

      public MetadataOuterClass.MetadataList getDefaultInstanceForType() {
        return MetadataOuterClass.MetadataList.getDefaultInstance();
      }

      public MetadataOuterClass.MetadataList build() {
        MetadataOuterClass.MetadataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MetadataOuterClass.MetadataList buildPartial() {
        MetadataOuterClass.MetadataList result = new MetadataOuterClass.MetadataList(this);
        int from_bitField0_ = bitField0_;
        if (metadataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            metadata_ = java.util.Collections.unmodifiableList(metadata_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MetadataOuterClass.MetadataList) {
          return mergeFrom((MetadataOuterClass.MetadataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MetadataOuterClass.MetadataList other) {
        if (other == MetadataOuterClass.MetadataList.getDefaultInstance()) return this;
        if (metadataBuilder_ == null) {
          if (!other.metadata_.isEmpty()) {
            if (metadata_.isEmpty()) {
              metadata_ = other.metadata_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMetadataIsMutable();
              metadata_.addAll(other.metadata_);
            }
            onChanged();
          }
        } else {
          if (!other.metadata_.isEmpty()) {
            if (metadataBuilder_.isEmpty()) {
              metadataBuilder_.dispose();
              metadataBuilder_ = null;
              metadata_ = other.metadata_;
              bitField0_ = (bitField0_ & ~0x00000001);
              metadataBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMetadataFieldBuilder() : null;
            } else {
              metadataBuilder_.addAllMessages(other.metadata_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MetadataOuterClass.MetadataList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MetadataOuterClass.MetadataList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Metadata> metadata_ =
        java.util.Collections.emptyList();
      private void ensureMetadataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          metadata_ = new java.util.ArrayList<Metadata>(metadata_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Metadata, Metadata.Builder, MetadataOrBuilder> metadataBuilder_;

      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public java.util.List<Metadata> getMetadataList() {
        if (metadataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metadata_);
        } else {
          return metadataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public int getMetadataCount() {
        if (metadataBuilder_ == null) {
          return metadata_.size();
        } else {
          return metadataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public MetadataOuterClass.Metadata getMetadata(int index) {
        if (metadataBuilder_ == null) {
          return metadata_.get(index);
        } else {
          return metadataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder setMetadata(
          int index, MetadataOuterClass.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.set(index, value);
          onChanged();
        } else {
          metadataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder setMetadata(
          int index, MetadataOuterClass.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.set(index, builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder addMetadata(MetadataOuterClass.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.add(value);
          onChanged();
        } else {
          metadataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder addMetadata(
          int index, MetadataOuterClass.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetadataIsMutable();
          metadata_.add(index, value);
          onChanged();
        } else {
          metadataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder addMetadata(
          MetadataOuterClass.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.add(builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder addMetadata(
          int index, MetadataOuterClass.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.add(index, builderForValue.build());
          onChanged();
        } else {
          metadataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder addAllMetadata(
          Iterable<? extends Metadata> values) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, metadata_);
          onChanged();
        } else {
          metadataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          metadataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public Builder removeMetadata(int index) {
        if (metadataBuilder_ == null) {
          ensureMetadataIsMutable();
          metadata_.remove(index);
          onChanged();
        } else {
          metadataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public MetadataOuterClass.Metadata.Builder getMetadataBuilder(
          int index) {
        return getMetadataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public MetadataOuterClass.MetadataOrBuilder getMetadataOrBuilder(
          int index) {
        if (metadataBuilder_ == null) {
          return metadata_.get(index);  } else {
          return metadataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public java.util.List<? extends MetadataOrBuilder>
           getMetadataOrBuilderList() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metadata_);
        }
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public MetadataOuterClass.Metadata.Builder addMetadataBuilder() {
        return getMetadataFieldBuilder().addBuilder(
            MetadataOuterClass.Metadata.getDefaultInstance());
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public MetadataOuterClass.Metadata.Builder addMetadataBuilder(
          int index) {
        return getMetadataFieldBuilder().addBuilder(
            index, MetadataOuterClass.Metadata.getDefaultInstance());
      }
      /**
       * <code>repeated .Metadata metadata = 1;</code>
       */
      public java.util.List<Metadata.Builder>
           getMetadataBuilderList() {
        return getMetadataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Metadata, Metadata.Builder, MetadataOrBuilder>
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Metadata, Metadata.Builder, MetadataOrBuilder>(
                  metadata_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MetadataList)
    }

    // @@protoc_insertion_point(class_scope:MetadataList)
    private static final MetadataOuterClass.MetadataList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MetadataOuterClass.MetadataList();
    }

    public static MetadataOuterClass.MetadataList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MetadataList>
        PARSER = new com.google.protobuf.AbstractParser<MetadataList>() {
      public MetadataList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MetadataList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetadataList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MetadataList> getParserForType() {
      return PARSER;
    }

    public MetadataOuterClass.MetadataList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MetadataList_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MetadataList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Metadata.proto\032\016Position.proto\"\322\003\n\010Met" +
      "adata\022\014\n\004UUID\030\001 \001(\t\022\034\n\004type\030\002 \001(\0162\016.Meta" +
      "data.Type\022\033\n\010position\030\003 \001(\0132\t.Position\022&" +
      "\n\tdirection\030\004 \001(\0162\023.Metadata.Direction\022\r" +
      "\n\005speed\030\005 \001(\002\022\017\n\007heading\030\006 \001(\002\022\016\n\006length" +
      "\030\007 \001(\002\022\r\n\005width\030\010 \001(\002\022\016\n\006height\030\t \001(\002\022\030\n" +
      "\020relativeDistance\030\n \001(\002\022\031\n\021relativeDista" +
      "nceX\030\013 \001(\002\022\031\n\021relativeDistanceY\030\014 \001(\002\"w\n" +
      "\tDirection\022\025\n\021DIRECTION_UNKNOWN\020\000\022\t\n\005FRO" +
      "NT\020\001\022\010\n\004REAR\020\002\022\016\n\nLEFT_FRONT\020\003\022\r\n\tLEFT_R",
      "EAR\020\004\022\017\n\013RIGHT_FRONT\020\005\022\016\n\nRIGHT_REAR\020\006\"=" +
      "\n\004Type\022\020\n\014TYPE_UNKNOWN\020\000\022\013\n\007Vehicle\020\001\022\r\n" +
      "\tNon_Motor\020\002\022\007\n\003MAN\020\003\"+\n\014MetadataList\022\033\n" +
      "\010metadata\030\001 \003(\0132\t.Metadatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PositionOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_descriptor,
        new String[] { "UUID", "Type", "Position", "Direction", "Speed", "Heading", "Length", "Width", "Height", "RelativeDistance", "RelativeDistanceX", "RelativeDistanceY", });
    internal_static_MetadataList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MetadataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MetadataList_descriptor,
        new String[] { "Metadata", });
    PositionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
