package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Position3D.proto

public final class Position3DOuterClass {
  private Position3DOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Position3DOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Position3D)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 1/10th micro degrees 302410033 表示北纬30.2410033度
     * </pre>
     *
     * <code>int64 latitude = 1;</code>
     */
    long getLatitude();

    /**
     * <pre>
     * 1/10th micro degrees 1202448229 表示东经120.2448229度
     * </pre>
     *
     * <code>int64 longitude = 2;</code>
     */
    long getLongitude();

    /**
     * <pre>
     * 10 cm units 改为以厘米为单位 1453 表示高位为14.53米
     * </pre>
     *
     * <code>int64 altitude = 3;</code>
     */
    long getAltitude();
  }
  /**
   * <pre>
   * 定义一个位置信息，坐标系 WGS84 大地坐标系
   * </pre>
   *
   * Protobuf type {@code Position3D}
   */
  public  static final class Position3D extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Position3D)
      Position3DOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Position3D.newBuilder() to construct.
    private Position3D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position3D() {
      latitude_ = 0L;
      longitude_ = 0L;
      altitude_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Position3D(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              latitude_ = input.readInt64();
              break;
            }
            case 16: {

              longitude_ = input.readInt64();
              break;
            }
            case 24: {

              altitude_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Position3DOuterClass.internal_static_Position3D_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Position3DOuterClass.internal_static_Position3D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Position3DOuterClass.Position3D.class, Position3DOuterClass.Position3D.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private long latitude_;
    /**
     * <pre>
     * 1/10th micro degrees 302410033 表示北纬30.2410033度
     * </pre>
     *
     * <code>int64 latitude = 1;</code>
     */
    public long getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private long longitude_;
    /**
     * <pre>
     * 1/10th micro degrees 1202448229 表示东经120.2448229度
     * </pre>
     *
     * <code>int64 longitude = 2;</code>
     */
    public long getLongitude() {
      return longitude_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 3;
    private long altitude_;
    /**
     * <pre>
     * 10 cm units 改为以厘米为单位 1453 表示高位为14.53米
     * </pre>
     *
     * <code>int64 altitude = 3;</code>
     */
    public long getAltitude() {
      return altitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0L) {
        output.writeInt64(1, latitude_);
      }
      if (longitude_ != 0L) {
        output.writeInt64(2, longitude_);
      }
      if (altitude_ != 0L) {
        output.writeInt64(3, altitude_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, latitude_);
      }
      if (longitude_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longitude_);
      }
      if (altitude_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, altitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Position3DOuterClass.Position3D)) {
        return super.equals(obj);
      }
      Position3DOuterClass.Position3D other = (Position3DOuterClass.Position3D) obj;

      boolean result = true;
      result = result && (getLatitude()
          == other.getLatitude());
      result = result && (getLongitude()
          == other.getLongitude());
      result = result && (getAltitude()
          == other.getAltitude());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLatitude());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongitude());
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAltitude());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Position3DOuterClass.Position3D parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Position3DOuterClass.Position3D parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Position3DOuterClass.Position3D parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Position3DOuterClass.Position3D parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Position3DOuterClass.Position3D parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Position3DOuterClass.Position3D parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Position3DOuterClass.Position3D parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Position3DOuterClass.Position3D parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Position3DOuterClass.Position3D parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Position3DOuterClass.Position3D parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Position3DOuterClass.Position3D parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Position3DOuterClass.Position3D parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Position3DOuterClass.Position3D prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义一个位置信息，坐标系 WGS84 大地坐标系
     * </pre>
     *
     * Protobuf type {@code Position3D}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Position3D)
        Position3DOuterClass.Position3DOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Position3DOuterClass.internal_static_Position3D_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Position3DOuterClass.internal_static_Position3D_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Position3DOuterClass.Position3D.class, Position3DOuterClass.Position3D.Builder.class);
      }

      // Construct using Position3DOuterClass.Position3D.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0L;

        longitude_ = 0L;

        altitude_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Position3DOuterClass.internal_static_Position3D_descriptor;
      }

      public Position3DOuterClass.Position3D getDefaultInstanceForType() {
        return Position3DOuterClass.Position3D.getDefaultInstance();
      }

      public Position3DOuterClass.Position3D build() {
        Position3DOuterClass.Position3D result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Position3DOuterClass.Position3D buildPartial() {
        Position3DOuterClass.Position3D result = new Position3DOuterClass.Position3D(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.altitude_ = altitude_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Position3DOuterClass.Position3D) {
          return mergeFrom((Position3DOuterClass.Position3D)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Position3DOuterClass.Position3D other) {
        if (other == Position3DOuterClass.Position3D.getDefaultInstance()) return this;
        if (other.getLatitude() != 0L) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0L) {
          setLongitude(other.getLongitude());
        }
        if (other.getAltitude() != 0L) {
          setAltitude(other.getAltitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Position3DOuterClass.Position3D parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Position3DOuterClass.Position3D) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long latitude_ ;
      /**
       * <pre>
       * 1/10th micro degrees 302410033 表示北纬30.2410033度
       * </pre>
       *
       * <code>int64 latitude = 1;</code>
       */
      public long getLatitude() {
        return latitude_;
      }
      /**
       * <pre>
       * 1/10th micro degrees 302410033 表示北纬30.2410033度
       * </pre>
       *
       * <code>int64 latitude = 1;</code>
       */
      public Builder setLatitude(long value) {

        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1/10th micro degrees 302410033 表示北纬30.2410033度
       * </pre>
       *
       * <code>int64 latitude = 1;</code>
       */
      public Builder clearLatitude() {

        latitude_ = 0L;
        onChanged();
        return this;
      }

      private long longitude_ ;
      /**
       * <pre>
       * 1/10th micro degrees 1202448229 表示东经120.2448229度
       * </pre>
       *
       * <code>int64 longitude = 2;</code>
       */
      public long getLongitude() {
        return longitude_;
      }
      /**
       * <pre>
       * 1/10th micro degrees 1202448229 表示东经120.2448229度
       * </pre>
       *
       * <code>int64 longitude = 2;</code>
       */
      public Builder setLongitude(long value) {

        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1/10th micro degrees 1202448229 表示东经120.2448229度
       * </pre>
       *
       * <code>int64 longitude = 2;</code>
       */
      public Builder clearLongitude() {

        longitude_ = 0L;
        onChanged();
        return this;
      }

      private long altitude_ ;
      /**
       * <pre>
       * 10 cm units 改为以厘米为单位 1453 表示高位为14.53米
       * </pre>
       *
       * <code>int64 altitude = 3;</code>
       */
      public long getAltitude() {
        return altitude_;
      }
      /**
       * <pre>
       * 10 cm units 改为以厘米为单位 1453 表示高位为14.53米
       * </pre>
       *
       * <code>int64 altitude = 3;</code>
       */
      public Builder setAltitude(long value) {

        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 10 cm units 改为以厘米为单位 1453 表示高位为14.53米
       * </pre>
       *
       * <code>int64 altitude = 3;</code>
       */
      public Builder clearAltitude() {

        altitude_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Position3D)
    }

    // @@protoc_insertion_point(class_scope:Position3D)
    private static final Position3DOuterClass.Position3D DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Position3DOuterClass.Position3D();
    }

    public static Position3DOuterClass.Position3D getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Position3D>
        PARSER = new com.google.protobuf.AbstractParser<Position3D>() {
      public Position3D parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Position3D(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Position3D> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Position3D> getParserForType() {
      return PARSER;
    }

    public Position3DOuterClass.Position3D getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Position3D_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Position3D_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020Position3D.proto\"C\n\nPosition3D\022\020\n\010lati" +
      "tude\030\001 \001(\003\022\021\n\tlongitude\030\002 \001(\003\022\020\n\010altitud" +
      "e\030\003 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Position3D_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Position3D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Position3D_descriptor,
        new String[] { "Latitude", "Longitude", "Altitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
