package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StationInformation.proto

public final class StationInformationOuterClass {
  private StationInformationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StationInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StationInformation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前站点
     * </pre>
     *
     * <code>.Station current = 1;</code>
     */
    boolean hasCurrent();
    /**
     * <pre>
     * 当前站点
     * </pre>
     *
     * <code>.Station current = 1;</code>
     */
    StationOuterClass.Station getCurrent();
    /**
     * <pre>
     * 当前站点
     * </pre>
     *
     * <code>.Station current = 1;</code>
     */
    StationOuterClass.StationOrBuilder getCurrentOrBuilder();

    /**
     * <pre>
     * 下一站点
     * </pre>
     *
     * <code>.Station next = 2;</code>
     */
    boolean hasNext();
    /**
     * <pre>
     * 下一站点
     * </pre>
     *
     * <code>.Station next = 2;</code>
     */
    StationOuterClass.Station getNext();
    /**
     * <pre>
     * 下一站点
     * </pre>
     *
     * <code>.Station next = 2;</code>
     */
    StationOuterClass.StationOrBuilder getNextOrBuilder();

    /**
     * <pre>
     * 车辆距离下一站点的实时距离,点位:米
     * </pre>
     *
     * <code>double nextStationDisntance = 3;</code>
     */
    double getNextStationDisntance();

    /**
     * <pre>
     * 车辆基于站点的动作:  -1 未知;1 进站;2 出站; 3 行驶在两个站点之间
     * </pre>
     *
     * <code>int32 action = 4;</code>
     */
    int getAction();
  }
  /**
   * <pre>
   *实时站点信息
   * </pre>
   *
   * Protobuf type {@code StationInformation}
   */
  public  static final class StationInformation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StationInformation)
      StationInformationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StationInformation.newBuilder() to construct.
    private StationInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StationInformation() {
      nextStationDisntance_ = 0D;
      action_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StationInformation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              StationOuterClass.Station.Builder subBuilder = null;
              if (current_ != null) {
                subBuilder = current_.toBuilder();
              }
              current_ = input.readMessage(StationOuterClass.Station.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(current_);
                current_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              StationOuterClass.Station.Builder subBuilder = null;
              if (next_ != null) {
                subBuilder = next_.toBuilder();
              }
              next_ = input.readMessage(StationOuterClass.Station.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(next_);
                next_ = subBuilder.buildPartial();
              }

              break;
            }
            case 25: {

              nextStationDisntance_ = input.readDouble();
              break;
            }
            case 32: {

              action_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StationInformationOuterClass.internal_static_StationInformation_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StationInformationOuterClass.internal_static_StationInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StationInformationOuterClass.StationInformation.class, StationInformationOuterClass.StationInformation.Builder.class);
    }

    public static final int CURRENT_FIELD_NUMBER = 1;
    private StationOuterClass.Station current_;
    /**
     * <pre>
     * 当前站点
     * </pre>
     *
     * <code>.Station current = 1;</code>
     */
    public boolean hasCurrent() {
      return current_ != null;
    }
    /**
     * <pre>
     * 当前站点
     * </pre>
     *
     * <code>.Station current = 1;</code>
     */
    public StationOuterClass.Station getCurrent() {
      return current_ == null ? StationOuterClass.Station.getDefaultInstance() : current_;
    }
    /**
     * <pre>
     * 当前站点
     * </pre>
     *
     * <code>.Station current = 1;</code>
     */
    public StationOuterClass.StationOrBuilder getCurrentOrBuilder() {
      return getCurrent();
    }

    public static final int NEXT_FIELD_NUMBER = 2;
    private StationOuterClass.Station next_;
    /**
     * <pre>
     * 下一站点
     * </pre>
     *
     * <code>.Station next = 2;</code>
     */
    public boolean hasNext() {
      return next_ != null;
    }
    /**
     * <pre>
     * 下一站点
     * </pre>
     *
     * <code>.Station next = 2;</code>
     */
    public StationOuterClass.Station getNext() {
      return next_ == null ? StationOuterClass.Station.getDefaultInstance() : next_;
    }
    /**
     * <pre>
     * 下一站点
     * </pre>
     *
     * <code>.Station next = 2;</code>
     */
    public StationOuterClass.StationOrBuilder getNextOrBuilder() {
      return getNext();
    }

    public static final int NEXTSTATIONDISNTANCE_FIELD_NUMBER = 3;
    private double nextStationDisntance_;
    /**
     * <pre>
     * 车辆距离下一站点的实时距离,点位:米
     * </pre>
     *
     * <code>double nextStationDisntance = 3;</code>
     */
    public double getNextStationDisntance() {
      return nextStationDisntance_;
    }

    public static final int ACTION_FIELD_NUMBER = 4;
    private int action_;
    /**
     * <pre>
     * 车辆基于站点的动作:  -1 未知;1 进站;2 出站; 3 行驶在两个站点之间
     * </pre>
     *
     * <code>int32 action = 4;</code>
     */
    public int getAction() {
      return action_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (current_ != null) {
        output.writeMessage(1, getCurrent());
      }
      if (next_ != null) {
        output.writeMessage(2, getNext());
      }
      if (nextStationDisntance_ != 0D) {
        output.writeDouble(3, nextStationDisntance_);
      }
      if (action_ != 0) {
        output.writeInt32(4, action_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (current_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCurrent());
      }
      if (next_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNext());
      }
      if (nextStationDisntance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, nextStationDisntance_);
      }
      if (action_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, action_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StationInformationOuterClass.StationInformation)) {
        return super.equals(obj);
      }
      StationInformationOuterClass.StationInformation other = (StationInformationOuterClass.StationInformation) obj;

      boolean result = true;
      result = result && (hasCurrent() == other.hasCurrent());
      if (hasCurrent()) {
        result = result && getCurrent()
            .equals(other.getCurrent());
      }
      result = result && (hasNext() == other.hasNext());
      if (hasNext()) {
        result = result && getNext()
            .equals(other.getNext());
      }
      result = result && (
          Double.doubleToLongBits(getNextStationDisntance())
          == Double.doubleToLongBits(
              other.getNextStationDisntance()));
      result = result && (getAction()
          == other.getAction());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCurrent()) {
        hash = (37 * hash) + CURRENT_FIELD_NUMBER;
        hash = (53 * hash) + getCurrent().hashCode();
      }
      if (hasNext()) {
        hash = (37 * hash) + NEXT_FIELD_NUMBER;
        hash = (53 * hash) + getNext().hashCode();
      }
      hash = (37 * hash) + NEXTSTATIONDISNTANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getNextStationDisntance()));
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StationInformationOuterClass.StationInformation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationInformationOuterClass.StationInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StationInformationOuterClass.StationInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationInformationOuterClass.StationInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StationInformationOuterClass.StationInformation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *实时站点信息
     * </pre>
     *
     * Protobuf type {@code StationInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StationInformation)
        StationInformationOuterClass.StationInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StationInformationOuterClass.internal_static_StationInformation_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StationInformationOuterClass.internal_static_StationInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StationInformationOuterClass.StationInformation.class, StationInformationOuterClass.StationInformation.Builder.class);
      }

      // Construct using StationInformationOuterClass.StationInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (currentBuilder_ == null) {
          current_ = null;
        } else {
          current_ = null;
          currentBuilder_ = null;
        }
        if (nextBuilder_ == null) {
          next_ = null;
        } else {
          next_ = null;
          nextBuilder_ = null;
        }
        nextStationDisntance_ = 0D;

        action_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StationInformationOuterClass.internal_static_StationInformation_descriptor;
      }

      public StationInformationOuterClass.StationInformation getDefaultInstanceForType() {
        return StationInformationOuterClass.StationInformation.getDefaultInstance();
      }

      public StationInformationOuterClass.StationInformation build() {
        StationInformationOuterClass.StationInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public StationInformationOuterClass.StationInformation buildPartial() {
        StationInformationOuterClass.StationInformation result = new StationInformationOuterClass.StationInformation(this);
        if (currentBuilder_ == null) {
          result.current_ = current_;
        } else {
          result.current_ = currentBuilder_.build();
        }
        if (nextBuilder_ == null) {
          result.next_ = next_;
        } else {
          result.next_ = nextBuilder_.build();
        }
        result.nextStationDisntance_ = nextStationDisntance_;
        result.action_ = action_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StationInformationOuterClass.StationInformation) {
          return mergeFrom((StationInformationOuterClass.StationInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StationInformationOuterClass.StationInformation other) {
        if (other == StationInformationOuterClass.StationInformation.getDefaultInstance()) return this;
        if (other.hasCurrent()) {
          mergeCurrent(other.getCurrent());
        }
        if (other.hasNext()) {
          mergeNext(other.getNext());
        }
        if (other.getNextStationDisntance() != 0D) {
          setNextStationDisntance(other.getNextStationDisntance());
        }
        if (other.getAction() != 0) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StationInformationOuterClass.StationInformation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StationInformationOuterClass.StationInformation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private StationOuterClass.Station current_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          StationOuterClass.Station, StationOuterClass.Station.Builder, StationOuterClass.StationOrBuilder> currentBuilder_;
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public boolean hasCurrent() {
        return currentBuilder_ != null || current_ != null;
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public StationOuterClass.Station getCurrent() {
        if (currentBuilder_ == null) {
          return current_ == null ? StationOuterClass.Station.getDefaultInstance() : current_;
        } else {
          return currentBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public Builder setCurrent(StationOuterClass.Station value) {
        if (currentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          current_ = value;
          onChanged();
        } else {
          currentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public Builder setCurrent(
          StationOuterClass.Station.Builder builderForValue) {
        if (currentBuilder_ == null) {
          current_ = builderForValue.build();
          onChanged();
        } else {
          currentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public Builder mergeCurrent(StationOuterClass.Station value) {
        if (currentBuilder_ == null) {
          if (current_ != null) {
            current_ =
              StationOuterClass.Station.newBuilder(current_).mergeFrom(value).buildPartial();
          } else {
            current_ = value;
          }
          onChanged();
        } else {
          currentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public Builder clearCurrent() {
        if (currentBuilder_ == null) {
          current_ = null;
          onChanged();
        } else {
          current_ = null;
          currentBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public StationOuterClass.Station.Builder getCurrentBuilder() {

        onChanged();
        return getCurrentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      public StationOuterClass.StationOrBuilder getCurrentOrBuilder() {
        if (currentBuilder_ != null) {
          return currentBuilder_.getMessageOrBuilder();
        } else {
          return current_ == null ?
              StationOuterClass.Station.getDefaultInstance() : current_;
        }
      }
      /**
       * <pre>
       * 当前站点
       * </pre>
       *
       * <code>.Station current = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          StationOuterClass.Station, StationOuterClass.Station.Builder, StationOuterClass.StationOrBuilder>
          getCurrentFieldBuilder() {
        if (currentBuilder_ == null) {
          currentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              StationOuterClass.Station, StationOuterClass.Station.Builder, StationOuterClass.StationOrBuilder>(
                  getCurrent(),
                  getParentForChildren(),
                  isClean());
          current_ = null;
        }
        return currentBuilder_;
      }

      private StationOuterClass.Station next_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          StationOuterClass.Station, StationOuterClass.Station.Builder, StationOuterClass.StationOrBuilder> nextBuilder_;
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public boolean hasNext() {
        return nextBuilder_ != null || next_ != null;
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public StationOuterClass.Station getNext() {
        if (nextBuilder_ == null) {
          return next_ == null ? StationOuterClass.Station.getDefaultInstance() : next_;
        } else {
          return nextBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public Builder setNext(StationOuterClass.Station value) {
        if (nextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          next_ = value;
          onChanged();
        } else {
          nextBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public Builder setNext(
          StationOuterClass.Station.Builder builderForValue) {
        if (nextBuilder_ == null) {
          next_ = builderForValue.build();
          onChanged();
        } else {
          nextBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public Builder mergeNext(StationOuterClass.Station value) {
        if (nextBuilder_ == null) {
          if (next_ != null) {
            next_ =
              StationOuterClass.Station.newBuilder(next_).mergeFrom(value).buildPartial();
          } else {
            next_ = value;
          }
          onChanged();
        } else {
          nextBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public Builder clearNext() {
        if (nextBuilder_ == null) {
          next_ = null;
          onChanged();
        } else {
          next_ = null;
          nextBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public StationOuterClass.Station.Builder getNextBuilder() {

        onChanged();
        return getNextFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      public StationOuterClass.StationOrBuilder getNextOrBuilder() {
        if (nextBuilder_ != null) {
          return nextBuilder_.getMessageOrBuilder();
        } else {
          return next_ == null ?
              StationOuterClass.Station.getDefaultInstance() : next_;
        }
      }
      /**
       * <pre>
       * 下一站点
       * </pre>
       *
       * <code>.Station next = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          StationOuterClass.Station, StationOuterClass.Station.Builder, StationOuterClass.StationOrBuilder>
          getNextFieldBuilder() {
        if (nextBuilder_ == null) {
          nextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              StationOuterClass.Station, StationOuterClass.Station.Builder, StationOuterClass.StationOrBuilder>(
                  getNext(),
                  getParentForChildren(),
                  isClean());
          next_ = null;
        }
        return nextBuilder_;
      }

      private double nextStationDisntance_ ;
      /**
       * <pre>
       * 车辆距离下一站点的实时距离,点位:米
       * </pre>
       *
       * <code>double nextStationDisntance = 3;</code>
       */
      public double getNextStationDisntance() {
        return nextStationDisntance_;
      }
      /**
       * <pre>
       * 车辆距离下一站点的实时距离,点位:米
       * </pre>
       *
       * <code>double nextStationDisntance = 3;</code>
       */
      public Builder setNextStationDisntance(double value) {

        nextStationDisntance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车辆距离下一站点的实时距离,点位:米
       * </pre>
       *
       * <code>double nextStationDisntance = 3;</code>
       */
      public Builder clearNextStationDisntance() {

        nextStationDisntance_ = 0D;
        onChanged();
        return this;
      }

      private int action_ ;
      /**
       * <pre>
       * 车辆基于站点的动作:  -1 未知;1 进站;2 出站; 3 行驶在两个站点之间
       * </pre>
       *
       * <code>int32 action = 4;</code>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <pre>
       * 车辆基于站点的动作:  -1 未知;1 进站;2 出站; 3 行驶在两个站点之间
       * </pre>
       *
       * <code>int32 action = 4;</code>
       */
      public Builder setAction(int value) {

        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车辆基于站点的动作:  -1 未知;1 进站;2 出站; 3 行驶在两个站点之间
       * </pre>
       *
       * <code>int32 action = 4;</code>
       */
      public Builder clearAction() {

        action_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StationInformation)
    }

    // @@protoc_insertion_point(class_scope:StationInformation)
    private static final StationInformationOuterClass.StationInformation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StationInformationOuterClass.StationInformation();
    }

    public static StationInformationOuterClass.StationInformation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StationInformation>
        PARSER = new com.google.protobuf.AbstractParser<StationInformation>() {
      public StationInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StationInformation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StationInformation> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StationInformation> getParserForType() {
      return PARSER;
    }

    public StationInformationOuterClass.StationInformation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StationInformation_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StationInformation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030StationInformation.proto\032\rStation.prot" +
      "o\"u\n\022StationInformation\022\031\n\007current\030\001 \001(\013" +
      "2\010.Station\022\026\n\004next\030\002 \001(\0132\010.Station\022\034\n\024ne" +
      "xtStationDisntance\030\003 \001(\001\022\016\n\006action\030\004 \001(\005" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          StationOuterClass.getDescriptor(),
        }, assigner);
    internal_static_StationInformation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StationInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StationInformation_descriptor,
        new String[] { "Current", "Next", "NextStationDisntance", "Action", });
    StationOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
