package com.matou.smartcar.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vehicle.proto

public final class VehicleOuterClass {
  private VehicleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VehicleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Vehicle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *字段车辆id,建议使用完整车牌号
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    String getUuid();
    /**
     * <pre>
     *字段车辆id,建议使用完整车牌号
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     *是否表示当前车辆
     * </pre>
     *
     * <code>bool isSelf = 2;</code>
     */
    boolean getIsSelf();

    /**
     * <pre>
     *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
     * </pre>
     *
     * <code>string brand = 3;</code>
     */
    String getBrand();
    /**
     * <pre>
     *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
     * </pre>
     *
     * <code>string brand = 3;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <pre>
     *车辆位置信息
     * </pre>
     *
     * <code>.Position position = 4;</code>
     */
    boolean hasPosition();
    /**
     * <pre>
     *车辆位置信息
     * </pre>
     *
     * <code>.Position position = 4;</code>
     */
    PositionOuterClass.Position getPosition();
    /**
     * <pre>
     *车辆位置信息
     * </pre>
     *
     * <code>.Position position = 4;</code>
     */
    PositionOuterClass.PositionOrBuilder getPositionOrBuilder();

    /**
     * <pre>
     * RTK状态
     * </pre>
     *
     * <code>int32 rtkStatue = 5;</code>
     */
    int getRtkStatue();

    /**
     * <pre>
     * 车辆行驶速度,千米/时
     * </pre>
     *
     * <code>float speed = 6;</code>
     */
    float getSpeed();

    /**
     * <pre>
     * 车辆航向角,正北为0，顺时针方向0-360
     * </pre>
     *
     * <code>float heading = 7;</code>
     */
    float getHeading();

    /**
     * <pre>
     *公交车门状态："0"表示车门全部关闭，"1"表示 1 号车门开启，"2"表示 2 号车门开启，"3" 表示所有车门均开启
     * </pre>
     *
     * <code>int32 selfCarDoorState = 8;</code>
     */
    int getSelfCarDoorState();

    /**
     * <pre>
     * 车辆扩展消息
     * </pre>
     *
     * <code>.VehicleExten vehicleExten = 9;</code>
     */
    boolean hasVehicleExten();
    /**
     * <pre>
     * 车辆扩展消息
     * </pre>
     *
     * <code>.VehicleExten vehicleExten = 9;</code>
     */
    VehicleExtenOuterClass.VehicleExten getVehicleExten();
    /**
     * <pre>
     * 车辆扩展消息
     * </pre>
     *
     * <code>.VehicleExten vehicleExten = 9;</code>
     */
    VehicleExtenOuterClass.VehicleExtenOrBuilder getVehicleExtenOrBuilder();
  }
  /**
   * Protobuf type {@code Vehicle}
   */
  public  static final class Vehicle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Vehicle)
      VehicleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vehicle.newBuilder() to construct.
    private Vehicle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vehicle() {
      uuid_ = "";
      isSelf_ = false;
      brand_ = "";
      rtkStatue_ = 0;
      speed_ = 0F;
      heading_ = 0F;
      selfCarDoorState_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vehicle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {

              isSelf_ = input.readBool();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 34: {
              PositionOuterClass.Position.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(PositionOuterClass.Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {

              rtkStatue_ = input.readInt32();
              break;
            }
            case 53: {

              speed_ = input.readFloat();
              break;
            }
            case 61: {

              heading_ = input.readFloat();
              break;
            }
            case 64: {

              selfCarDoorState_ = input.readInt32();
              break;
            }
            case 74: {
              VehicleExtenOuterClass.VehicleExten.Builder subBuilder = null;
              if (vehicleExten_ != null) {
                subBuilder = vehicleExten_.toBuilder();
              }
              vehicleExten_ = input.readMessage(VehicleExtenOuterClass.VehicleExten.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vehicleExten_);
                vehicleExten_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VehicleOuterClass.internal_static_Vehicle_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VehicleOuterClass.internal_static_Vehicle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VehicleOuterClass.Vehicle.class, VehicleOuterClass.Vehicle.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile Object uuid_;
    /**
     * <pre>
     *字段车辆id,建议使用完整车牌号
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public String getUuid() {
      Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *字段车辆id,建议使用完整车牌号
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSELF_FIELD_NUMBER = 2;
    private boolean isSelf_;
    /**
     * <pre>
     *是否表示当前车辆
     * </pre>
     *
     * <code>bool isSelf = 2;</code>
     */
    public boolean getIsSelf() {
      return isSelf_;
    }

    public static final int BRAND_FIELD_NUMBER = 3;
    private volatile Object brand_;
    /**
     * <pre>
     *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
     * </pre>
     *
     * <code>string brand = 3;</code>
     */
    public String getBrand() {
      Object ref = brand_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
     * </pre>
     *
     * <code>string brand = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 4;
    private PositionOuterClass.Position position_;
    /**
     * <pre>
     *车辆位置信息
     * </pre>
     *
     * <code>.Position position = 4;</code>
     */
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <pre>
     *车辆位置信息
     * </pre>
     *
     * <code>.Position position = 4;</code>
     */
    public PositionOuterClass.Position getPosition() {
      return position_ == null ? PositionOuterClass.Position.getDefaultInstance() : position_;
    }
    /**
     * <pre>
     *车辆位置信息
     * </pre>
     *
     * <code>.Position position = 4;</code>
     */
    public PositionOuterClass.PositionOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int RTKSTATUE_FIELD_NUMBER = 5;
    private int rtkStatue_;
    /**
     * <pre>
     * RTK状态
     * </pre>
     *
     * <code>int32 rtkStatue = 5;</code>
     */
    public int getRtkStatue() {
      return rtkStatue_;
    }

    public static final int SPEED_FIELD_NUMBER = 6;
    private float speed_;
    /**
     * <pre>
     * 车辆行驶速度,千米/时
     * </pre>
     *
     * <code>float speed = 6;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    public static final int HEADING_FIELD_NUMBER = 7;
    private float heading_;
    /**
     * <pre>
     * 车辆航向角,正北为0，顺时针方向0-360
     * </pre>
     *
     * <code>float heading = 7;</code>
     */
    public float getHeading() {
      return heading_;
    }

    public static final int SELFCARDOORSTATE_FIELD_NUMBER = 8;
    private int selfCarDoorState_;
    /**
     * <pre>
     *公交车门状态："0"表示车门全部关闭，"1"表示 1 号车门开启，"2"表示 2 号车门开启，"3" 表示所有车门均开启
     * </pre>
     *
     * <code>int32 selfCarDoorState = 8;</code>
     */
    public int getSelfCarDoorState() {
      return selfCarDoorState_;
    }

    public static final int VEHICLEEXTEN_FIELD_NUMBER = 9;
    private VehicleExtenOuterClass.VehicleExten vehicleExten_;
    /**
     * <pre>
     * 车辆扩展消息
     * </pre>
     *
     * <code>.VehicleExten vehicleExten = 9;</code>
     */
    public boolean hasVehicleExten() {
      return vehicleExten_ != null;
    }
    /**
     * <pre>
     * 车辆扩展消息
     * </pre>
     *
     * <code>.VehicleExten vehicleExten = 9;</code>
     */
    public VehicleExtenOuterClass.VehicleExten getVehicleExten() {
      return vehicleExten_ == null ? VehicleExtenOuterClass.VehicleExten.getDefaultInstance() : vehicleExten_;
    }
    /**
     * <pre>
     * 车辆扩展消息
     * </pre>
     *
     * <code>.VehicleExten vehicleExten = 9;</code>
     */
    public VehicleExtenOuterClass.VehicleExtenOrBuilder getVehicleExtenOrBuilder() {
      return getVehicleExten();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (isSelf_ != false) {
        output.writeBool(2, isSelf_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, brand_);
      }
      if (position_ != null) {
        output.writeMessage(4, getPosition());
      }
      if (rtkStatue_ != 0) {
        output.writeInt32(5, rtkStatue_);
      }
      if (speed_ != 0F) {
        output.writeFloat(6, speed_);
      }
      if (heading_ != 0F) {
        output.writeFloat(7, heading_);
      }
      if (selfCarDoorState_ != 0) {
        output.writeInt32(8, selfCarDoorState_);
      }
      if (vehicleExten_ != null) {
        output.writeMessage(9, getVehicleExten());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (isSelf_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSelf_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, brand_);
      }
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPosition());
      }
      if (rtkStatue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, rtkStatue_);
      }
      if (speed_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, speed_);
      }
      if (heading_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, heading_);
      }
      if (selfCarDoorState_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, selfCarDoorState_);
      }
      if (vehicleExten_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getVehicleExten());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VehicleOuterClass.Vehicle)) {
        return super.equals(obj);
      }
      VehicleOuterClass.Vehicle other = (VehicleOuterClass.Vehicle) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && (getIsSelf()
          == other.getIsSelf());
      result = result && getBrand()
          .equals(other.getBrand());
      result = result && (hasPosition() == other.hasPosition());
      if (hasPosition()) {
        result = result && getPosition()
            .equals(other.getPosition());
      }
      result = result && (getRtkStatue()
          == other.getRtkStatue());
      result = result && (
          Float.floatToIntBits(getSpeed())
          == Float.floatToIntBits(
              other.getSpeed()));
      result = result && (
          Float.floatToIntBits(getHeading())
          == Float.floatToIntBits(
              other.getHeading()));
      result = result && (getSelfCarDoorState()
          == other.getSelfCarDoorState());
      result = result && (hasVehicleExten() == other.hasVehicleExten());
      if (hasVehicleExten()) {
        result = result && getVehicleExten()
            .equals(other.getVehicleExten());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + ISSELF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSelf());
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      hash = (37 * hash) + RTKSTATUE_FIELD_NUMBER;
      hash = (53 * hash) + getRtkStatue();
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + HEADING_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getHeading());
      hash = (37 * hash) + SELFCARDOORSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getSelfCarDoorState();
      if (hasVehicleExten()) {
        hash = (37 * hash) + VEHICLEEXTEN_FIELD_NUMBER;
        hash = (53 * hash) + getVehicleExten().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VehicleOuterClass.Vehicle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VehicleOuterClass.Vehicle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VehicleOuterClass.Vehicle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VehicleOuterClass.Vehicle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VehicleOuterClass.Vehicle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VehicleOuterClass.Vehicle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VehicleOuterClass.Vehicle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VehicleOuterClass.Vehicle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VehicleOuterClass.Vehicle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VehicleOuterClass.Vehicle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VehicleOuterClass.Vehicle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VehicleOuterClass.Vehicle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VehicleOuterClass.Vehicle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vehicle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Vehicle)
        VehicleOuterClass.VehicleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VehicleOuterClass.internal_static_Vehicle_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VehicleOuterClass.internal_static_Vehicle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VehicleOuterClass.Vehicle.class, VehicleOuterClass.Vehicle.Builder.class);
      }

      // Construct using VehicleOuterClass.Vehicle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        isSelf_ = false;

        brand_ = "";

        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        rtkStatue_ = 0;

        speed_ = 0F;

        heading_ = 0F;

        selfCarDoorState_ = 0;

        if (vehicleExtenBuilder_ == null) {
          vehicleExten_ = null;
        } else {
          vehicleExten_ = null;
          vehicleExtenBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VehicleOuterClass.internal_static_Vehicle_descriptor;
      }

      public VehicleOuterClass.Vehicle getDefaultInstanceForType() {
        return VehicleOuterClass.Vehicle.getDefaultInstance();
      }

      public VehicleOuterClass.Vehicle build() {
        VehicleOuterClass.Vehicle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public VehicleOuterClass.Vehicle buildPartial() {
        VehicleOuterClass.Vehicle result = new VehicleOuterClass.Vehicle(this);
        result.uuid_ = uuid_;
        result.isSelf_ = isSelf_;
        result.brand_ = brand_;
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.rtkStatue_ = rtkStatue_;
        result.speed_ = speed_;
        result.heading_ = heading_;
        result.selfCarDoorState_ = selfCarDoorState_;
        if (vehicleExtenBuilder_ == null) {
          result.vehicleExten_ = vehicleExten_;
        } else {
          result.vehicleExten_ = vehicleExtenBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VehicleOuterClass.Vehicle) {
          return mergeFrom((VehicleOuterClass.Vehicle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VehicleOuterClass.Vehicle other) {
        if (other == VehicleOuterClass.Vehicle.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.getIsSelf() != false) {
          setIsSelf(other.getIsSelf());
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.getRtkStatue() != 0) {
          setRtkStatue(other.getRtkStatue());
        }
        if (other.getSpeed() != 0F) {
          setSpeed(other.getSpeed());
        }
        if (other.getHeading() != 0F) {
          setHeading(other.getHeading());
        }
        if (other.getSelfCarDoorState() != 0) {
          setSelfCarDoorState(other.getSelfCarDoorState());
        }
        if (other.hasVehicleExten()) {
          mergeVehicleExten(other.getVehicleExten());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VehicleOuterClass.Vehicle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VehicleOuterClass.Vehicle) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object uuid_ = "";
      /**
       * <pre>
       *字段车辆id,建议使用完整车牌号
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public String getUuid() {
        Object ref = uuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *字段车辆id,建议使用完整车牌号
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *字段车辆id,建议使用完整车牌号
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *字段车辆id,建议使用完整车牌号
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder clearUuid() {

        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *字段车辆id,建议使用完整车牌号
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        uuid_ = value;
        onChanged();
        return this;
      }

      private boolean isSelf_ ;
      /**
       * <pre>
       *是否表示当前车辆
       * </pre>
       *
       * <code>bool isSelf = 2;</code>
       */
      public boolean getIsSelf() {
        return isSelf_;
      }
      /**
       * <pre>
       *是否表示当前车辆
       * </pre>
       *
       * <code>bool isSelf = 2;</code>
       */
      public Builder setIsSelf(boolean value) {

        isSelf_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否表示当前车辆
       * </pre>
       *
       * <code>bool isSelf = 2;</code>
       */
      public Builder clearIsSelf() {

        isSelf_ = false;
        onChanged();
        return this;
      }

      private Object brand_ = "";
      /**
       * <pre>
       *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
       * </pre>
       *
       * <code>string brand = 3;</code>
       */
      public String getBrand() {
        Object ref = brand_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
       * </pre>
       *
       * <code>string brand = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
       * </pre>
       *
       * <code>string brand = 3;</code>
       */
      public Builder setBrand(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
       * </pre>
       *
       * <code>string brand = 3;</code>
       */
      public Builder clearBrand() {

        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车辆品牌 "0" 表示金龙, "1" 表示牧越,"3" autoTalk,"4" 京东无人车
       * </pre>
       *
       * <code>string brand = 3;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        brand_ = value;
        onChanged();
        return this;
      }

      private PositionOuterClass.Position position_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          PositionOuterClass.Position, PositionOuterClass.Position.Builder, PositionOuterClass.PositionOrBuilder> positionBuilder_;
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public PositionOuterClass.Position getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? PositionOuterClass.Position.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public Builder setPosition(PositionOuterClass.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public Builder setPosition(
          PositionOuterClass.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public Builder mergePosition(PositionOuterClass.Position value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              PositionOuterClass.Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public PositionOuterClass.Position.Builder getPositionBuilder() {

        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      public PositionOuterClass.PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              PositionOuterClass.Position.getDefaultInstance() : position_;
        }
      }
      /**
       * <pre>
       *车辆位置信息
       * </pre>
       *
       * <code>.Position position = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PositionOuterClass.Position, PositionOuterClass.Position.Builder, PositionOuterClass.PositionOrBuilder>
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PositionOuterClass.Position, PositionOuterClass.Position.Builder, PositionOuterClass.PositionOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private int rtkStatue_ ;
      /**
       * <pre>
       * RTK状态
       * </pre>
       *
       * <code>int32 rtkStatue = 5;</code>
       */
      public int getRtkStatue() {
        return rtkStatue_;
      }
      /**
       * <pre>
       * RTK状态
       * </pre>
       *
       * <code>int32 rtkStatue = 5;</code>
       */
      public Builder setRtkStatue(int value) {

        rtkStatue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * RTK状态
       * </pre>
       *
       * <code>int32 rtkStatue = 5;</code>
       */
      public Builder clearRtkStatue() {

        rtkStatue_ = 0;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <pre>
       * 车辆行驶速度,千米/时
       * </pre>
       *
       * <code>float speed = 6;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <pre>
       * 车辆行驶速度,千米/时
       * </pre>
       *
       * <code>float speed = 6;</code>
       */
      public Builder setSpeed(float value) {

        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车辆行驶速度,千米/时
       * </pre>
       *
       * <code>float speed = 6;</code>
       */
      public Builder clearSpeed() {

        speed_ = 0F;
        onChanged();
        return this;
      }

      private float heading_ ;
      /**
       * <pre>
       * 车辆航向角,正北为0，顺时针方向0-360
       * </pre>
       *
       * <code>float heading = 7;</code>
       */
      public float getHeading() {
        return heading_;
      }
      /**
       * <pre>
       * 车辆航向角,正北为0，顺时针方向0-360
       * </pre>
       *
       * <code>float heading = 7;</code>
       */
      public Builder setHeading(float value) {

        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 车辆航向角,正北为0，顺时针方向0-360
       * </pre>
       *
       * <code>float heading = 7;</code>
       */
      public Builder clearHeading() {

        heading_ = 0F;
        onChanged();
        return this;
      }

      private int selfCarDoorState_ ;
      /**
       * <pre>
       *公交车门状态："0"表示车门全部关闭，"1"表示 1 号车门开启，"2"表示 2 号车门开启，"3" 表示所有车门均开启
       * </pre>
       *
       * <code>int32 selfCarDoorState = 8;</code>
       */
      public int getSelfCarDoorState() {
        return selfCarDoorState_;
      }
      /**
       * <pre>
       *公交车门状态："0"表示车门全部关闭，"1"表示 1 号车门开启，"2"表示 2 号车门开启，"3" 表示所有车门均开启
       * </pre>
       *
       * <code>int32 selfCarDoorState = 8;</code>
       */
      public Builder setSelfCarDoorState(int value) {

        selfCarDoorState_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *公交车门状态："0"表示车门全部关闭，"1"表示 1 号车门开启，"2"表示 2 号车门开启，"3" 表示所有车门均开启
       * </pre>
       *
       * <code>int32 selfCarDoorState = 8;</code>
       */
      public Builder clearSelfCarDoorState() {

        selfCarDoorState_ = 0;
        onChanged();
        return this;
      }

      private VehicleExtenOuterClass.VehicleExten vehicleExten_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          VehicleExtenOuterClass.VehicleExten, VehicleExtenOuterClass.VehicleExten.Builder, VehicleExtenOuterClass.VehicleExtenOrBuilder> vehicleExtenBuilder_;
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public boolean hasVehicleExten() {
        return vehicleExtenBuilder_ != null || vehicleExten_ != null;
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public VehicleExtenOuterClass.VehicleExten getVehicleExten() {
        if (vehicleExtenBuilder_ == null) {
          return vehicleExten_ == null ? VehicleExtenOuterClass.VehicleExten.getDefaultInstance() : vehicleExten_;
        } else {
          return vehicleExtenBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public Builder setVehicleExten(VehicleExtenOuterClass.VehicleExten value) {
        if (vehicleExtenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vehicleExten_ = value;
          onChanged();
        } else {
          vehicleExtenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public Builder setVehicleExten(
          VehicleExtenOuterClass.VehicleExten.Builder builderForValue) {
        if (vehicleExtenBuilder_ == null) {
          vehicleExten_ = builderForValue.build();
          onChanged();
        } else {
          vehicleExtenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public Builder mergeVehicleExten(VehicleExtenOuterClass.VehicleExten value) {
        if (vehicleExtenBuilder_ == null) {
          if (vehicleExten_ != null) {
            vehicleExten_ =
              VehicleExtenOuterClass.VehicleExten.newBuilder(vehicleExten_).mergeFrom(value).buildPartial();
          } else {
            vehicleExten_ = value;
          }
          onChanged();
        } else {
          vehicleExtenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public Builder clearVehicleExten() {
        if (vehicleExtenBuilder_ == null) {
          vehicleExten_ = null;
          onChanged();
        } else {
          vehicleExten_ = null;
          vehicleExtenBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public VehicleExtenOuterClass.VehicleExten.Builder getVehicleExtenBuilder() {

        onChanged();
        return getVehicleExtenFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      public VehicleExtenOuterClass.VehicleExtenOrBuilder getVehicleExtenOrBuilder() {
        if (vehicleExtenBuilder_ != null) {
          return vehicleExtenBuilder_.getMessageOrBuilder();
        } else {
          return vehicleExten_ == null ?
              VehicleExtenOuterClass.VehicleExten.getDefaultInstance() : vehicleExten_;
        }
      }
      /**
       * <pre>
       * 车辆扩展消息
       * </pre>
       *
       * <code>.VehicleExten vehicleExten = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          VehicleExtenOuterClass.VehicleExten, VehicleExtenOuterClass.VehicleExten.Builder, VehicleExtenOuterClass.VehicleExtenOrBuilder>
          getVehicleExtenFieldBuilder() {
        if (vehicleExtenBuilder_ == null) {
          vehicleExtenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              VehicleExtenOuterClass.VehicleExten, VehicleExtenOuterClass.VehicleExten.Builder, VehicleExtenOuterClass.VehicleExtenOrBuilder>(
                  getVehicleExten(),
                  getParentForChildren(),
                  isClean());
          vehicleExten_ = null;
        }
        return vehicleExtenBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Vehicle)
    }

    // @@protoc_insertion_point(class_scope:Vehicle)
    private static final VehicleOuterClass.Vehicle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VehicleOuterClass.Vehicle();
    }

    public static VehicleOuterClass.Vehicle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vehicle>
        PARSER = new com.google.protobuf.AbstractParser<Vehicle>() {
      public Vehicle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Vehicle(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vehicle> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Vehicle> getParserForType() {
      return PARSER;
    }

    public VehicleOuterClass.Vehicle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vehicle_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vehicle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rVehicle.proto\032\016Position.proto\032\022Vehicle" +
      "Exten.proto\"\305\001\n\007Vehicle\022\014\n\004uuid\030\001 \001(\t\022\016\n" +
      "\006isSelf\030\002 \001(\010\022\r\n\005brand\030\003 \001(\t\022\033\n\010position" +
      "\030\004 \001(\0132\t.Position\022\021\n\trtkStatue\030\005 \001(\005\022\r\n\005" +
      "speed\030\006 \001(\002\022\017\n\007heading\030\007 \001(\002\022\030\n\020selfCarD" +
      "oorState\030\010 \001(\005\022#\n\014vehicleExten\030\t \001(\0132\r.V" +
      "ehicleExtenb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PositionOuterClass.getDescriptor(),
          VehicleExtenOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Vehicle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Vehicle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vehicle_descriptor,
        new String[] { "Uuid", "IsSelf", "Brand", "Position", "RtkStatue", "Speed", "Heading", "SelfCarDoorState", "VehicleExten", });
    PositionOuterClass.getDescriptor();
    VehicleExtenOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
